"""
INQUISITOR Publisher — My Documents Push & Notification
========================================================
Pushes updated court-ready filing stacks to My Documents and
generates changelogs. Optionally sends Windows toast notifications.

Story 2.5: My Documents Push & Notification
"""
import sys
import os
import shutil
import json
from pathlib import Path
from datetime import datetime
from typing import Optional

_shared = Path(__file__).parent.parent / "shared"
if str(_shared) not in sys.path:
    sys.path.insert(0, str(_shared))

from autonomos_config import (
    DIR_MY_DOCS_FILINGS, DIR_OMEGA_FILINGS, LITIGOS_ROOT,
    LANE_REGISTRY, sha256_file,
)

# Lane → My Documents subdirectory
LANE_DIRS = {
    "A": "Lane_A_Custody",
    "B": "Lane_B_Housing",
    "C": "Lane_C_Convergence",
    "D": "Lane_D_PPO",
    "E": "Lane_E_Misconduct",
    "F": "Lane_F_Appellate",
}


def ensure_my_docs_structure():
    """Create the My Documents filing structure."""
    DIR_MY_DOCS_FILINGS.mkdir(parents=True, exist_ok=True)
    for lane, dirname in LANE_DIRS.items():
        lane_dir = DIR_MY_DOCS_FILINGS / dirname
        lane_dir.mkdir(exist_ok=True)
    readme = DIR_MY_DOCS_FILINGS / "README.md"
    if not readme.exists():
        readme.write_text(
            "# LitigationOS Court-Ready Filings\n\n"
            "This directory is auto-managed by AUTONOMOS INQUISITOR.\n"
            "Updated filing stacks are pushed here automatically when new evidence is processed.\n\n"
            "**DO NOT manually edit files here** — they will be overwritten on next update.\n"
            "Edit source filings in `C:\\Users\\andre\\LitigationOS\\06_FILINGS\\`.\n",
            encoding="utf-8"
        )


def push_filing_stack(lane: str, filing_name: str, source_dir: Path | None = None,
                      trigger_reason: str = "") -> dict:
    """
    Push a filing stack to My Documents.
    Returns: {"success": bool, "files_copied": int, "dest_dir": str, "error": str}
    """
    lane_dirname = LANE_DIRS.get(lane, f"Lane_{lane}")
    dest_dir = DIR_MY_DOCS_FILINGS / lane_dirname / filing_name

    if source_dir is None:
        # Look in OMEGA_GENERATED
        source_dir = DIR_OMEGA_FILINGS / "OMEGA_GENERATED" / "court_ready"
        if not source_dir.exists():
            source_dir = DIR_OMEGA_FILINGS / "OMEGA_GENERATED"

    if not source_dir.exists():
        return {"success": False, "files_copied": 0, "dest_dir": str(dest_dir),
                "error": f"Source dir not found: {source_dir}"}

    # Create versioned destination
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    versioned_dest = dest_dir / f"v_{timestamp}"
    versioned_dest.mkdir(parents=True, exist_ok=True)

    # Copy files
    files_copied = 0
    try:
        for item in source_dir.rglob("*"):
            if item.is_file():
                rel = item.relative_to(source_dir)
                target = versioned_dest / rel
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(str(item), str(target))
                files_copied += 1
    except Exception as e:
        return {"success": False, "files_copied": files_copied,
                "dest_dir": str(versioned_dest), "error": str(e)}

    # Generate changelog
    _write_changelog(dest_dir, filing_name, trigger_reason, files_copied, timestamp)

    # Update "latest" symlink/copy
    latest = dest_dir / "LATEST"
    if latest.exists():
        shutil.rmtree(str(latest), ignore_errors=True)
    try:
        shutil.copytree(str(versioned_dest), str(latest))
    except Exception:
        pass

    return {"success": True, "files_copied": files_copied,
            "dest_dir": str(versioned_dest), "error": ""}


def _write_changelog(dest_dir: Path, filing_name: str, reason: str,
                     files_count: int, timestamp: str):
    """Append to the per-lane CHANGELOG.md."""
    changelog = dest_dir / "CHANGELOG.md"
    entry = (
        f"\n## {timestamp} — {filing_name}\n"
        f"- **Trigger:** {reason or 'New evidence processed'}\n"
        f"- **Files:** {files_count}\n"
        f"- **Updated at:** {datetime.now().isoformat()}\n"
    )
    mode = "a" if changelog.exists() else "w"
    header = "# Filing Stack Changelog\n\nAuto-generated by AUTONOMOS INQUISITOR.\n" if mode == "w" else ""
    with open(changelog, mode, encoding="utf-8") as f:
        if header:
            f.write(header)
        f.write(entry)


def send_notification(title: str, message: str):
    """Send a Windows toast notification (best-effort)."""
    try:
        from plyer import notification
        notification.notify(title=title, message=message, timeout=10)
        return True
    except ImportError:
        pass
    try:
        from win10toast import ToastNotifier
        toast = ToastNotifier()
        toast.show_toast(title, message, duration=10, threaded=True)
        return True
    except ImportError:
        pass
    # Fallback: just print
    print(f"[NOTIFICATION] {title}: {message}", file=sys.stderr)
    return False


def push_all_lanes() -> dict:
    """Push latest filing stacks for all lanes to My Documents."""
    ensure_my_docs_structure()
    results = {}
    omega_dir = DIR_OMEGA_FILINGS / "OMEGA_GENERATED"
    if not omega_dir.exists():
        return {"error": f"OMEGA dir not found: {omega_dir}"}

    for lane, lane_dir_name in LANE_DIRS.items():
        court_ready = omega_dir / "court_ready"
        if court_ready.exists():
            result = push_filing_stack(lane, "court_ready", court_ready, "Manual push")
            results[lane] = result
    return results


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="INQUISITOR Publisher")
    parser.add_argument("action", choices=["push", "push-all", "setup", "notify-test"])
    parser.add_argument("--lane", default="")
    parser.add_argument("--filing", default="court_ready")
    args = parser.parse_args()

    if args.action == "setup":
        ensure_my_docs_structure()
        print(f"Created filing structure at {DIR_MY_DOCS_FILINGS}")
    elif args.action == "push-all":
        results = push_all_lanes()
        print(json.dumps(results, indent=2))
    elif args.action == "push" and args.lane:
        result = push_filing_stack(args.lane, args.filing)
        print(json.dumps(result, indent=2))
    elif args.action == "notify-test":
        send_notification("AUTONOMOS Test", "Filing stack updated successfully!")
    else:
        parser.print_help()
