# -*- mode: python ; coding: utf-8 -*-
# THEMANBEARPIG V5.0 — PyInstaller Spec (one-dir mode)
# Generated by scripts/mbp_build.py
#
# Build with:  pyinstaller THEMANBEARPIG.spec
#
# One-dir mode is RECOMMENDED for this project because:
#   - mbp_brain.db is 257+ MB — one-file would extract it to temp on every launch
#   - Faster startup: no temp extraction needed
#   - Easier to update graph_data.json without rebuilding

block_cipher = None

a = Analysis(
    ['C:\\Users\\andre\\LitigationOS\\scripts\\mbp_app.py'],
    pathex=['C:\\Users\\andre\\LitigationOS'],
    binaries=[],
    datas=[
        ('C:\\Users\\andre\\LitigationOS\\08_MEDIA\\MANBEARPIG_V5\\graph_data.json', 'MANBEARPIG_V5'),
        ('C:\\Users\\andre\\LitigationOS\\08_MEDIA\\MANBEARPIG_V5\\index.html', 'MANBEARPIG_V5'),
        ('C:\\Users\\andre\\LitigationOS\\mbp_brain.db', '.'),
    ],
    hiddenimports=['webview', 'webview.platforms.edgechromium', 'webview.platforms.winforms', 'clr', 'clr_loader', 'pythonnet', 'System', 'System.Windows.Forms', 'System.Drawing', 'System.Threading', 'http.server', 'socketserver'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "pandas", "scipy"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='THEMANBEARPIG',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    icon=None,  # No icon.ico found — add one to 08_MEDIA/MANBEARPIG_V5/
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='THEMANBEARPIG',
)
