"""
DELTA99 Ω∞ — Windows Service Wrapper
======================================
Registers SENTINEL + INQUISITOR as Windows services for boot-time auto-start.
Supports both pywin32 (preferred) and NSSM (fallback) approaches.

Depends on: d99-self-heal
"""
import sys
import os
import json
import subprocess
import time
from pathlib import Path
from datetime import datetime

_shared = Path(__file__).parent.parent / "shared"
if str(_shared) not in sys.path:
    sys.path.insert(0, str(_shared))

from autonomos_config import AUTONOMOS_ROOT, LITIGOS_ROOT

SERVICE_CONFIG = {
    "SENTINEL": {
        "name": "LitigationOS_SENTINEL",
        "display": "LitigationOS SENTINEL Drive Monitor",
        "description": "Autonomous drive organization daemon for LitigationOS",
        "script": str(AUTONOMOS_ROOT / "sentinel" / "sentinel.py"),
        "args": ["--daemon"],
        "start_type": "auto",
    },
    "INQUISITOR": {
        "name": "LitigationOS_INQUISITOR",
        "display": "LitigationOS INQUISITOR File Watchdog",
        "description": "Intelligent file watchdog and auto-analysis daemon for LitigationOS",
        "script": str(AUTONOMOS_ROOT / "inquisitor" / "inquisitor.py"),
        "args": ["--daemon"],
        "start_type": "auto",
    },
}

LOG_DIR = LITIGOS_ROOT / "00_SYSTEM" / "logs"
STATUS_FILE = AUTONOMOS_ROOT / "service_status.json"


def _find_python() -> str:
    """Find the Python executable."""
    candidates = [
        sys.executable,
        "python",
        "python3",
        r"C:\Python314\python.exe",
        r"C:\Python312\python.exe",
        r"C:\Python311\python.exe",
    ]
    for c in candidates:
        try:
            result = subprocess.run(
                [c, "--version"],
                capture_output=True, text=True, timeout=10
            )
            if result.returncode == 0:
                return c
        except (subprocess.SubprocessError, FileNotFoundError, OSError):
            continue
    return sys.executable


def _check_pywin32() -> bool:
    """Check if pywin32 is available."""
    try:
        import win32serviceutil
        import win32service
        return True
    except ImportError:
        return False


def _check_nssm() -> str | None:
    """Check if NSSM is available and return path."""
    candidates = [
        r"C:\nssm\nssm.exe",
        r"C:\tools\nssm.exe",
        "nssm",
    ]
    for c in candidates:
        try:
            result = subprocess.run(
                [c, "version"],
                capture_output=True, text=True, timeout=10
            )
            if result.returncode == 0:
                return c
        except (subprocess.SubprocessError, FileNotFoundError, OSError):
            continue
    return None


def _generate_pywin32_service(service_key: str) -> str:
    """Generate a pywin32 service script."""
    config = SERVICE_CONFIG[service_key]
    script_path = config["script"].replace("\\", "\\\\")

    return f'''"""
Auto-generated Windows Service for {config["display"]}
Generated by DELTA99 Windows Service Wrapper
"""
import sys
import os
import subprocess
import win32serviceutil
import win32service
import win32event
import servicemanager

class {service_key}Service(win32serviceutil.ServiceFramework):
    _svc_name_ = "{config['name']}"
    _svc_display_name_ = "{config['display']}"
    _svc_description_ = "{config['description']}"

    def __init__(self, args):
        win32serviceutil.ServiceFramework.__init__(self, args)
        self.hWaitStop = win32event.CreateEvent(None, 0, 0, None)
        self.process = None

    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        win32event.SetEvent(self.hWaitStop)
        if self.process:
            self.process.terminate()
            try:
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.process.kill()

    def SvcDoRun(self):
        servicemanager.LogMsg(
            servicemanager.EVENTLOG_INFORMATION_TYPE,
            servicemanager.PYS_SERVICE_STARTED,
            (self._svc_name_, "")
        )
        python_exe = sys.executable
        script = r"{script_path}"
        self.process = subprocess.Popen(
            [python_exe, script] + {config.get("args", [])},
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        win32event.WaitForSingleObject(self.hWaitStop, win32event.INFINITE)

if __name__ == "__main__":
    win32serviceutil.HandleCommandLine({service_key}Service)
'''


def _generate_nssm_script() -> str:
    """Generate NSSM installation script."""
    python = _find_python().replace("\\", "\\\\")
    lines = [
        "@echo off",
        f'set PYTHON="{python}"',
        "",
    ]

    for key, config in SERVICE_CONFIG.items():
        script = config["script"].replace("\\", "\\\\")
        args = " ".join(config.get("args", []))
        lines.extend([
            f'echo Installing {config["display"]}...',
            f'nssm install {config["name"]} %PYTHON% "{script}" {args}',
            f'nssm set {config["name"]} DisplayName "{config["display"]}"',
            f'nssm set {config["name"]} Description "{config["description"]}"',
            f'nssm set {config["name"]} Start SERVICE_AUTO_START',
            f'nssm set {config["name"]} AppStdout "{LOG_DIR}\\\\{key.lower()}_stdout.log"',
            f'nssm set {config["name"]} AppStderr "{LOG_DIR}\\\\{key.lower()}_stderr.log"',
            f'nssm set {config["name"]} AppRotateFiles 1',
            f'nssm set {config["name"]} AppRotateBytes 10485760',
            f'echo Starting {config["name"]}...',
            f'nssm start {config["name"]}',
            "",
        ])

    lines.append("echo All services installed and started.")
    return "\n".join(lines)


def _generate_task_scheduler_xml(service_key: str) -> str:
    """Generate Windows Task Scheduler XML as fallback."""
    config = SERVICE_CONFIG[service_key]
    python = _find_python()
    script = config["script"]
    args = " ".join(config.get("args", []))

    return f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>{config['description']}</Description>
    <Author>LitigationOS DELTA99</Author>
  </RegistrationInfo>
  <Triggers>
    <BootTrigger>
      <Enabled>true</Enabled>
      <Delay>PT60S</Delay>
    </BootTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <RestartOnFailure>
      <Interval>PT5M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{python}</Command>
      <Arguments>{script} {args}</Arguments>
      <WorkingDirectory>{AUTONOMOS_ROOT}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>"""


def install(method: str = "auto") -> dict:
    """Install services using best available method."""
    results = {"method": method, "services": {}, "fallback_files": []}

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    output_dir = AUTONOMOS_ROOT / "services"
    output_dir.mkdir(parents=True, exist_ok=True)

    if method == "auto":
        if _check_pywin32():
            method = "pywin32"
        elif _check_nssm():
            method = "nssm"
        else:
            method = "task_scheduler"

    results["method"] = method

    if method == "pywin32":
        for key in SERVICE_CONFIG:
            svc_code = _generate_pywin32_service(key)
            svc_file = output_dir / f"{key.lower()}_service.py"
            svc_file.write_text(svc_code, encoding="utf-8")
            results["services"][key] = {
                "file": str(svc_file),
                "install_cmd": f"python {svc_file} install",
                "start_cmd": f"python {svc_file} start",
            }
            results["fallback_files"].append(str(svc_file))

    elif method == "nssm":
        nssm_script = _generate_nssm_script()
        nssm_file = output_dir / "install_services.bat"
        nssm_file.write_text(nssm_script, encoding="utf-8")
        results["services"]["all"] = {
            "file": str(nssm_file),
            "install_cmd": str(nssm_file),
        }
        results["fallback_files"].append(str(nssm_file))

    elif method == "task_scheduler":
        for key in SERVICE_CONFIG:
            xml = _generate_task_scheduler_xml(key)
            xml_file = output_dir / f"{key.lower()}_task.xml"
            xml_file.write_text(xml, encoding="utf-16")
            import_cmd = f'schtasks /Create /TN "LitigationOS\\{key}" /XML "{xml_file}" /F'
            results["services"][key] = {
                "file": str(xml_file),
                "install_cmd": import_cmd,
            }
            results["fallback_files"].append(str(xml_file))

    # Save status
    STATUS_FILE.parent.mkdir(parents=True, exist_ok=True)
    status = {
        "method": method,
        "installed_at": datetime.now().isoformat(),
        "services": results["services"],
    }
    STATUS_FILE.write_text(json.dumps(status, indent=2), encoding="utf-8")

    return results


def status() -> dict:
    """Check service installation status."""
    if STATUS_FILE.exists():
        return json.loads(STATUS_FILE.read_text(encoding="utf-8"))
    return {"installed": False, "message": "No services installed"}


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"
    if cmd == "install":
        method = sys.argv[2] if len(sys.argv) > 2 else "auto"
        print(json.dumps(install(method), indent=2))
    elif cmd == "status":
        print(json.dumps(status(), indent=2))
    else:
        print(f"Usage: python windows_service.py install|status [method]")
