#!/usr/bin/env python3
"""
next_best_step_report.py (v42) — NON-INTERPRETIVE NEXT STEP RECOMMENDER

Inspects expected pipeline artifacts in a bundle directory and emits a single-best-action plan.
Does not invent facts or law; only reports which gates are PASS/FAIL and what file/fields to provide next.

Usage:
  python tools/next_best_step_report.py --bundle-root <path> --out-json outputs/next_best_step.json
"""
import argparse, json, os

def exists_nonzero(p):
    return os.path.exists(p) and os.path.getsize(p) > 0

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--bundle-root", required=True)
    ap.add_argument("--out-json", required=True)
    args=ap.parse_args()

    root=args.bundle_root
    def p(rel): return os.path.join(root, rel)

    gates=[]
    gates.extend(_v48_extra_gates(root))
    def gate(name, ok, detail=""):
        gates.append({"gate":name,"status":"PASS" if ok else "FAIL","detail":detail})

    # Gate 1: FTS DB
    fts = p("outputs/authority_anchor_fts.sqlite")
    gate("FTS_DB_PRESENT", exists_nonzero(fts), f"expected {fts}")

    # Gate 2: Facts validation
    facts = p("outputs/facts.jsonl")
    facts_val = p("outputs/facts_validation.json")
    gate("FACTS_PRESENT", exists_nonzero(facts), f"expected {facts}")
    gate("FACTS_VALIDATION_PRESENT", exists_nonzero(facts_val), f"expected {facts_val}")

    # Gate 3: Intents
    intents = p("outputs/intents.json")
    gate("INTENTS_PRESENT", exists_nonzero(intents), f"expected {intents}")

    # Gate 4: Vehicle registry
    vreg = p("docs/vehicle_registry_seed_v35.json")
    gate("VEHICLE_REGISTRY_PRESENT", exists_nonzero(vreg), f"expected {vreg}")
    mined = p("outputs/vehicle_registry_mined_v39.json")
    gate("VEHICLE_REGISTRY_MINED_PRESENT", exists_nonzero(mined), f"optional helper {mined}")

    # Gate 5: Propositions for triples
    props = p("outputs/propositions.json")
    triples = p("outputs/authority_triples_candidates.jsonl")
    gate("PROPOSITIONS_PRESENT", exists_nonzero(props), f"expected {props}")
    gate("TRIPLES_PRESENT", exists_nonzero(triples), f"expected {triples}")

    # Gate 6: Docket/events for deadlines
    docket_entries = p("outputs/docket_entries_in.json")
    events = p("outputs/events_out.json")
    deadlines_events = p("outputs/deadlines_events_out.json")
    deadlines = p("outputs/deadlines.json")
    gate("DOCKET_ENTRIES_PRESENT", exists_nonzero(docket_entries), f"optional {docket_entries}")
    gate("EVENTS_PRESENT", exists_nonzero(events), f"expected {events} (from docket ingest)")
    gate("DEADLINES_EVENTS_PRESENT", exists_nonzero(deadlines_events), f"expected {deadlines_events}")
    gate("DEADLINES_PRESENT", exists_nonzero(deadlines), f"expected {deadlines}")

    # Gate 7: Claim packet
    packet = p("outputs/claim_packet_candidate.json")
    gate("CLAIM_PACKET_PRESENT", exists_nonzero(packet), f"expected {packet}")

    # Determine next best action
    # Priority: get facts w/ pinpoints passing validation.
    status="READY"
    inputs_needed=[]
    commands=[]
    single=""
    why=""

    if not exists_nonzero(fts):
        status="BLOCKED"
        single="Build authority FTS database from authority_shards.jsonl"
        why="Retrieval layer missing."
        inputs_needed.append("outputs/authority_shards.jsonl (generated by ingest)")
        commands.append("python tools/authority_anchor_index.py --in-jsonl outputs/authority_shards.jsonl --out-sqlite outputs/authority_anchor_fts.sqlite")
    elif not exists_nonzero(facts):
        status="BLOCKED"
        single="Create facts.jsonl with real pinpoints (page/line/bates/timecode)"
        why="No fact layer; cannot proceed to vehicle mapping or claims packaging."
        inputs_needed.append("outputs/facts.jsonl (one fact per line with pinpoint locator)")
        commands.append("python tools/facts_template_from_manifest.py --manifest-json manifest.json --out-facts-jsonl outputs/facts.jsonl")
    elif not exists_nonzero(facts_val):
        status="BLOCKED"
        single="Run v34 pinpoint validator on facts.jsonl"
        why="Facts must pass fail-closed gate before any downstream use."
        inputs_needed.append("outputs/facts.jsonl")
        commands.append("python tools/facts_pinpoint_validate.py --facts-jsonl outputs/facts.jsonl --manifest-json manifest.json --out-json outputs/facts_validation.json")
    elif not exists_nonzero(intents):
        status="BLOCKED"
        single="Write intents.json (desired relief / procedural intents)"
        why="Vehicle router needs intents to retrieve candidate authority."
        inputs_needed.append("outputs/intents.json")
        commands.append('echo \'{"intents":[{"id":"R1","text":"<INTENT TEXT HERE>"}]}\' > outputs/intents.json')
    elif not exists_nonzero(props):
        status="BLOCKED"
        single="Write propositions.json for authority triples (proposition text + query)"
        why="Authority triples require explicit propositions; system will not invent them."
        inputs_needed.append("outputs/propositions.json")
        commands.append('echo \'{"items":[{"id":"P1","proposition":"<PROPOSITION HERE>","query":"<FTS QUERY HERE>"}]}\' > outputs/propositions.json')
    elif not exists_nonzero(deadlines_events):
        status="BLOCKED"
        single="Normalize docket entries into deadlines_events_out.json"
        why="Deadlines feed requires event specs; offsets/rule_basis remain operator-supplied."
        inputs_needed.append("outputs/docket_entries_in.json or a docket text file to parse")
        commands.append("python tools/docket_mifile_ingest_candidate.py --in-json outputs/docket_entries_in.json --events-out-json outputs/events_out.json --deadlines-events-out-json outputs/deadlines_events_out.json")
    elif not exists_nonzero(packet):
        status="READY"
        single="Run pipeline runner to assemble claim packet (candidate-only)"
        why="All prerequisites appear present to assemble the candidate packet."
        commands.append("python tools/run_claim_pipeline_v39.py --bundle-root . --fts-db outputs/authority_anchor_fts.sqlite --facts-jsonl outputs/facts.jsonl --intents-json outputs/intents.json --propositions-json outputs/propositions.json --events-json outputs/deadlines_events_out.json --out-dir outputs")
    else:
        status="READY"
        single="Validate/curate candidate outputs and promote to VERIFIED layers"
        why="Candidate packet exists; next step is human validation and tightening pinpoints."
        inputs_needed.append("verified caselaw list (if using cases); curated vehicle registry; audited deadlines rule-basis")
        commands.append("Review outputs/claim_packet_candidate_v39.json and promote validated items to VERIFIED store.")

    out={
      "status": status,
      "single_best_action": single,
      "why": why,
      "gates": gates,
      "inputs_needed": inputs_needed,
      "commands": commands,
      "meta": {"confidence":"NON_INTERPRETIVE","version":"v42"}
    }
    os.makedirs(os.path.dirname(args.out_json), exist_ok=True)
    json.dump(out, open(args.out_json,"w",encoding="utf-8"), indent=2, ensure_ascii=False)
    print("OK status=", status)

if __name__=="__main__":
    main()


# v48 PATCH: additional gates for docket ingest + caselaw verification
def _v48_extra_gates(root):
    g=[]
    p=os.path.join(root,'outputs','docket_events.json')
    if os.path.exists(p) and os.path.getsize(p)>0:
        g.append({'gate':'DOCKET_INGEST','status':'PASS','detail':'outputs/docket_events.json present'})
    else:
        g.append({'gate':'DOCKET_INGEST','status':'FAIL','detail':'missing outputs/docket_events.json (run docket_mifile_ingest_v48.py)'})
    # DEADLINES gate
    pd=os.path.join(root,'outputs','deadlines.json')
    if os.path.exists(pd) and os.path.getsize(pd)>0:
        g.append({'gate':'DEADLINES','status':'PASS','detail':'outputs/deadlines.json present'})
    else:
        g.append({'gate':'DEADLINES','status':'FAIL','detail':'missing outputs/deadlines.json (run deadlines_from_docket_v49.py)'})
    p2=os.path.join(root,'outputs','caselaw_verified.json')
    if os.path.exists(p2) and os.path.getsize(p2)>0:
        try:
            data=json.load(open(p2,'r',encoding='utf-8'))
            items=data.get('items') or []
            unv=[it for it in items if (it.get('status') or 'UNVERIFIED')=='UNVERIFIED']
            g.append({'gate':'CASELAW_GOVERNANCE','status':'PASS' if not unv else 'FAIL','detail':f'{len(unv)} unverified'})
        except Exception as e:
            g.append({'gate':'CASELAW_GOVERNANCE','status':'FAIL','detail':'caselaw_verified.json unreadable'})
    else:
        g.append({'gate':'CASELAW_GOVERNANCE','status':'FAIL','detail':'missing outputs/caselaw_verified.json'})
    return g
