"""Legal notices, disclaimers, and compliance text for LitigationOS.

This module centralizes all legal language displayed to users in the CLI,
GUI, generated documents, and marketing materials. Import from here instead
of hardcoding legal text elsewhere.
"""

# ---------------------------------------------------------------------------
# Core disclaimer — displayed on first run, splash screen, and About dialog
# ---------------------------------------------------------------------------
DISCLAIMER = (
    "LitigationOS is an AI-powered legal research and document preparation "
    "tool. It is designed to assist users in organizing case materials, "
    "generating court-formatted documents, tracking deadlines, and analyzing "
    "evidence. LitigationOS is not a law firm, does not practice law, and "
    "does not provide legal representation. Use of this software does not "
    "create an attorney-client relationship."
)

# ---------------------------------------------------------------------------
# Not-legal-advice notice — appended to every generated document footer
# ---------------------------------------------------------------------------
NOT_LEGAL_ADVICE = (
    "This software does not provide legal advice. The information and "
    "documents generated by LitigationOS are for informational and "
    "organizational purposes only. They are not a substitute for the advice "
    "of a licensed attorney. You should consult with a qualified legal "
    "professional before making any legal decisions or filing any documents "
    "with a court. You are solely responsible for reviewing, verifying, and "
    "approving all content before submission."
)

# ---------------------------------------------------------------------------
# AI-specific disclaimer — shown when AI features are used
# ---------------------------------------------------------------------------
AI_DISCLAIMER = (
    "LitigationOS uses artificial intelligence for document classification, "
    "entity extraction, evidence scoring, and other analytical features. "
    "AI-generated outputs are assistive suggestions, not authoritative legal "
    "analysis. All AI processing occurs locally on your device — no data is "
    "sent to external servers. You must independently verify all AI-generated "
    "content before relying on it."
)

# ---------------------------------------------------------------------------
# Data privacy notice — shown during onboarding and in Settings
# ---------------------------------------------------------------------------
PRIVACY_NOTICE = (
    "LitigationOS is a local-first application. All case data, evidence, "
    "filings, and analysis results are stored exclusively on your device. "
    "No data is transmitted to external servers, cloud services, or third "
    "parties. Optional AI features (Ollama, ChromaDB) also run locally. "
    "Anonymous crash reporting is available only with explicit opt-in."
)

# ---------------------------------------------------------------------------
# URLs — used in GUI footer links and CLI output
# ---------------------------------------------------------------------------
TERMS_OF_SERVICE_URL = "https://litigationos.com/terms"
PRIVACY_POLICY_URL = "https://litigationos.com/privacy"
DOCUMENTATION_URL = "https://litigationos.com/docs"
SUPPORT_URL = "https://litigationos.com/support"
GITHUB_URL = "https://github.com/litigationos/litigationos"

# ---------------------------------------------------------------------------
# Document footer — appended to every generated court document
# ---------------------------------------------------------------------------
DOCUMENT_FOOTER_NOTICE = (
    "Prepared with LitigationOS. This document was generated using automated "
    "tools and has not been reviewed by an attorney unless otherwise noted. "
    "The filer is solely responsible for its contents and accuracy."
)

# ---------------------------------------------------------------------------
# Jurisdiction disclaimer — shown when jurisdiction plugin is loaded
# ---------------------------------------------------------------------------
JURISDICTION_DISCLAIMER = (
    "LitigationOS includes court rules, forms, and deadline calculations for "
    "supported jurisdictions. Court rules and procedures change frequently. "
    "While we strive to keep this information current, you must verify all "
    "rules, deadlines, and form requirements against the official sources for "
    "your jurisdiction before filing."
)

# ---------------------------------------------------------------------------
# Version and copyright
# ---------------------------------------------------------------------------
COPYRIGHT = "Copyright (c) 2025 LitigationOS Contributors"
LICENSE_TYPE = "See LICENSE file for details"
