"""
OMEGA Phase 7B: SYNTHESIS Merge (Append-Only)
Merges new citation counts into SYNTHESIS_DATA.json and updates MASTER_*.csv files.
Copy-before-modify pattern with atomic writes.
"""
import csv
import io
import json
import os
import sys
import time
from pathlib import Path

from config import (
    MASTER_ROOT, sha256_file,
    get_cyclepack_dir, report_progress,
)
from safety import write_phase_checkpoint, is_phase_done, write_touchlog

MASTER_CSV_FILES = {
    "MASTER_EVIDENCE_INDEX.csv": "sha256",
    "MASTER_VIOLATIONS.csv": "violation_id",
    "MASTER_PERSONS.csv": "name",
    "MASTER_TIMELINE.csv": "date",
    "MASTER_CITATIONS.csv": "citation",
}

SIZE_WARN_FACTOR = 2.0


def _atomic_write(path: Path, content: str, encoding: str = "utf-8"):
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding=encoding)
    os.replace(str(tmp), str(path))


def _load_atoms(cycle_dir: Path) -> list[dict]:
    atoms = []
    for fname in ("fact_atoms.jsonl", "citation_atoms.jsonl",
                   "event_atoms.jsonl", "person_atoms.jsonl"):
        fpath = cycle_dir / fname
        if not fpath.exists():
            fpath = cycle_dir / "atoms" / fname
        if fpath.exists():
            for line in fpath.read_text(encoding="utf-8", errors="replace").splitlines():
                line = line.strip()
                if line:
                    try:
                        atoms.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
    return atoms


def _load_delta_csv(cycle_dir: Path, fname: str) -> list[dict]:
    """Load delta rows generated by earlier phases."""
    rows = []
    # Check for a delta file matching the master name
    delta_name = fname.replace(".csv", "_delta.csv")
    for candidate in (cycle_dir / delta_name, cycle_dir / fname):
        if candidate.exists():
            try:
                text = candidate.read_text(encoding="utf-8", errors="replace")
                reader = csv.DictReader(io.StringIO(text))
                rows.extend(list(reader))
            except (FileNotFoundError, json.JSONDecodeError, KeyError, csv.Error) as e:
                print(f"[PHASE7B] Warning: {e}", file=sys.stderr)
            break
    return rows


def _merge_synthesis(cycle_dir: Path, atoms: list[dict], dry_run: bool) -> dict:
    synth_path = MASTER_ROOT / "SYNTHESIS_DATA.json"
    synth: dict = {}
    original_size = 0

    if synth_path.exists():
        original_size = synth_path.stat().st_size
        try:
            synth = json.loads(synth_path.read_text(encoding="utf-8", errors="replace"))
        except (json.JSONDecodeError, OSError):
            synth = {}

    # Build new citation counts from atoms
    new_counts: dict[str, int] = {}
    for atom in atoms:
        if atom.get("atom_type") == "citation":
            cite = atom.get("citation") or atom.get("text", "")
            cite = cite.strip()[:200]
            if cite:
                new_counts[cite] = new_counts.get(cite, 0) + 1

    # Merge into synthesis
    existing_cites = synth.get("citation_counts", {})
    merged = 0
    for cite, cnt in new_counts.items():
        existing_cites[cite] = existing_cites.get(cite, 0) + cnt
        merged += 1
    synth["citation_counts"] = existing_cites
    synth["last_merge_ts"] = time.strftime("%Y-%m-%dT%H:%M:%S")

    if not dry_run:
        sha_before = sha256_file(synth_path) if synth_path.exists() else None
        write_touchlog(cycle_dir, "phase7b", str(synth_path), "merge_synthesis", sha_before=sha_before)

        new_content = json.dumps(synth, indent=2, ensure_ascii=False)
        new_size = len(new_content.encode("utf-8"))

        if original_size > 0 and new_size > original_size * SIZE_WARN_FACTOR:
            print(f"[PHASE7B] WARNING: SYNTHESIS_DATA.json grew from {original_size:,} to {new_size:,} bytes (>{SIZE_WARN_FACTOR}x)", file=sys.stderr)

        _atomic_write(synth_path, new_content)
        sha_after = sha256_file(synth_path)
        write_touchlog(cycle_dir, "phase7b", str(synth_path), "merge_synthesis_done", sha_after=sha_after)

    return {"citations_merged": merged}


def _merge_master_csv(cycle_dir: Path, fname: str, id_field: str,
                      atoms: list[dict], dry_run: bool) -> dict:
    master_path = MASTER_ROOT / fname
    original_size = master_path.stat().st_size if master_path.exists() else 0

    # Load existing rows
    existing_rows: list[dict] = []
    existing_ids: set[str] = set()
    fieldnames: list[str] = []

    if master_path.exists():
        try:
            text = master_path.read_text(encoding="utf-8", errors="replace")
            reader = csv.DictReader(io.StringIO(text))
            fieldnames = list(reader.fieldnames or [])
            for row in reader:
                existing_rows.append(row)
                val = row.get(id_field)
                if val:
                    existing_ids.add(val.strip())
        except (FileNotFoundError, json.JSONDecodeError, KeyError, csv.Error) as e:
            print(f"[PHASE7B] Warning: {e}", file=sys.stderr)

    # Load delta rows from cycle
    delta_rows = _load_delta_csv(cycle_dir, fname)

    # Also generate rows from atoms based on CSV type
    atom_rows: list[dict] = []
    if "EVIDENCE" in fname:
        for a in atoms:
            if a.get("atom_type") == "fact":
                sha = a.get("source_sha256", "")
                if sha and sha not in existing_ids:
                    atom_rows.append({"sha256": sha, "source": a.get("source_path", ""),
                                      "type": "fact", "text": (a.get("text", "") or "")[:500]})
    elif "VIOLATIONS" in fname:
        for a in atoms:
            if a.get("atom_type") == "fact" and a.get("violation"):
                vid = a.get("violation_id", a.get("source_sha256", "")[:16])
                if vid and vid not in existing_ids:
                    atom_rows.append({"violation_id": vid, "type": a.get("violation", ""),
                                      "text": (a.get("text", "") or "")[:500],
                                      "source_sha256": a.get("source_sha256", "")})
    elif "PERSONS" in fname:
        for a in atoms:
            if a.get("atom_type") == "person":
                name = a.get("name", a.get("text", ""))
                if name and name not in existing_ids:
                    atom_rows.append({"name": name, "role": a.get("role", ""),
                                      "source_sha256": a.get("source_sha256", "")})
    elif "TIMELINE" in fname:
        for a in atoms:
            if a.get("atom_type") == "event":
                date = a.get("date", "")
                if date and date not in existing_ids:
                    atom_rows.append({"date": date, "event": (a.get("text", "") or "")[:500],
                                      "source_sha256": a.get("source_sha256", "")})
    elif "CITATIONS" in fname:
        for a in atoms:
            if a.get("atom_type") == "citation":
                cite = a.get("citation", a.get("text", ""))
                if cite and cite not in existing_ids:
                    atom_rows.append({"citation": cite, "type": a.get("cite_type", ""),
                                      "source_sha256": a.get("source_sha256", "")})

    # Combine deltas
    all_new: list[dict] = []
    for row in delta_rows + atom_rows:
        val = row.get(id_field)
        if val and val.strip() not in existing_ids:
            all_new.append(row)
            existing_ids.add(val.strip())

    if not all_new:
        return {"file": fname, "appended": 0}

    # Merge fieldnames
    for row in all_new:
        for k in row:
            if k not in fieldnames:
                fieldnames.append(k)
    if not fieldnames:
        fieldnames = list(all_new[0].keys())

    if not dry_run:
        sha_before = sha256_file(master_path) if master_path.exists() else None
        write_touchlog(cycle_dir, "phase7b", str(master_path), "merge_csv", sha_before=sha_before)

        merged = existing_rows + all_new
        buf = io.StringIO()
        w = csv.DictWriter(buf, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        w.writerows(merged)
        new_content = buf.getvalue()
        new_size = len(new_content.encode("utf-8"))

        if original_size > 0 and new_size > original_size * SIZE_WARN_FACTOR:
            print(f"[PHASE7B] WARNING: {fname} grew from {original_size:,} to {new_size:,} bytes (>{SIZE_WARN_FACTOR}x)", file=sys.stderr)

        _atomic_write(master_path, new_content)
        sha_after = sha256_file(master_path)
        write_touchlog(cycle_dir, "phase7b", str(master_path), "merge_csv_done", sha_after=sha_after)

    return {"file": fname, "appended": len(all_new)}


def run_synthesis_merge(cycle_dir: Path, dry_run: bool = False):
    if is_phase_done(cycle_dir, "phase7b"):
        print("[PHASE7B] Already complete, skipping", file=sys.stderr)
        return

    atoms = _load_atoms(cycle_dir)
    if not atoms:
        print("[PHASE7B] No atom stores found, skipping", file=sys.stderr)
        write_phase_checkpoint(cycle_dir, "phase7b", {"status": "done", "merged": 0, "reason": "no_atoms"})
        return

    print(f"[PHASE7B] Loaded {len(atoms):,} atoms, merging into master files...", file=sys.stderr)
    start = time.time()
    results: list[dict] = []

    # 1. SYNTHESIS_DATA.json
    synth_result = _merge_synthesis(cycle_dir, atoms, dry_run)
    results.append({"target": "SYNTHESIS_DATA.json", **synth_result})

    # 2. MASTER_*.csv files
    for fname, id_field in MASTER_CSV_FILES.items():
        csv_result = _merge_master_csv(cycle_dir, fname, id_field, atoms, dry_run)
        results.append(csv_result)
        report_progress("phase7b", len(results), len(MASTER_CSV_FILES) + 1)

    elapsed = time.time() - start
    total_appended = sum(r.get("appended", 0) for r in results) + synth_result.get("citations_merged", 0)
    print(f"[PHASE7B] Merge complete: {total_appended:,} entries across {len(results)} targets in {elapsed:.0f}s", file=sys.stderr)

    if not dry_run:
        stats = {"results": results, "total_appended": total_appended, "elapsed_seconds": round(elapsed, 1)}
        (cycle_dir / "synthesis_merge_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")
        write_phase_checkpoint(cycle_dir, "phase7b", {"status": "done", "appended": total_appended, "elapsed": f"{elapsed:.0f}s"})


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Phase 7B: Synthesis Merge")
    parser.add_argument("--cycle-ts", default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    from config import CYCLE_TS
    run_synthesis_merge(get_cyclepack_dir(args.cycle_ts or CYCLE_TS), args.dry_run)
