"""C:\ Space Recovery — Phase 1: __pycache__ purge + orphan cleanup.
SAFE: __pycache__ is auto-regenerated by Python. .pyc files are bytecode cache.
This frees space without losing any source code or evidence.
"""
import os
import shutil
from pathlib import Path
from datetime import datetime

REPO = Path(r"C:\Users\andre\LitigationOS")
LOG = []

def purge_pycache(root: Path) -> tuple:
    """Remove all __pycache__ directories under root. Returns (dirs_removed, bytes_freed)."""
    dirs_removed = 0
    bytes_freed = 0
    
    for dirpath, dirnames, filenames in os.walk(root):
        # Skip .git directory entirely
        if '.git' in dirpath.split(os.sep):
            continue
        
        for d in list(dirnames):
            if d == '__pycache__':
                cache_dir = Path(dirpath) / d
                try:
                    # Calculate size first
                    dir_size = sum(f.stat().st_size for f in cache_dir.rglob('*') if f.is_file())
                    shutil.rmtree(cache_dir)
                    dirs_removed += 1
                    bytes_freed += dir_size
                    LOG.append(f"  Removed: {cache_dir} ({dir_size/1024:.0f} KB)")
                except Exception as e:
                    LOG.append(f"  SKIP: {cache_dir} — {e}")
                dirnames.remove(d)
    
    return dirs_removed, bytes_freed

def purge_orphan_pyc(root: Path) -> tuple:
    """Remove .pyc files not inside __pycache__."""
    files_removed = 0
    bytes_freed = 0
    
    for f in root.rglob("*.pyc"):
        if '.git' in str(f):
            continue
        if '__pycache__' not in str(f):
            try:
                size = f.stat().st_size
                f.unlink()
                files_removed += 1
                bytes_freed += size
                LOG.append(f"  Orphan .pyc removed: {f} ({size/1024:.0f} KB)")
            except Exception as e:
                LOG.append(f"  SKIP .pyc: {f} — {e}")
    
    return files_removed, bytes_freed

def find_temp_files(root: Path) -> list:
    """Find temp/log files that could be cleaned."""
    temp_patterns = ['*.tmp', '*.log', '*.bak', '*.swp']
    found = []
    for pat in temp_patterns:
        for f in root.rglob(pat):
            if '.git' in str(f):
                continue
            try:
                found.append((str(f), f.stat().st_size))
            except:
                pass
    return found

def main():
    print("=" * 60)
    print("C:\\ SPACE RECOVERY — Phase 1")
    print("=" * 60)
    
    # 1. Purge __pycache__
    print("\n🗑️  Purging __pycache__ directories...")
    dirs, cache_bytes = purge_pycache(REPO)
    print(f"   Removed {dirs} __pycache__ dirs, freed {cache_bytes/1024/1024:.1f} MB")
    
    # Also check pytools_venv __pycache__
    venv_path = REPO / "pytools_venv"
    if venv_path.exists():
        print("\n🗑️  Purging __pycache__ in pytools_venv...")
        vdirs, vbytes = purge_pycache(venv_path)
        dirs += vdirs
        cache_bytes += vbytes
        print(f"   Removed {vdirs} venv __pycache__ dirs, freed {vbytes/1024/1024:.1f} MB")
    
    # 2. Orphan .pyc files
    print("\n🗑️  Removing orphan .pyc files...")
    pyc_files, pyc_bytes = purge_orphan_pyc(REPO)
    print(f"   Removed {pyc_files} orphan .pyc files, freed {pyc_bytes/1024/1024:.1f} MB")
    
    # 3. Find temp files (report only, don't delete)
    print("\n🔍 Scanning for temp/log files...")
    temps = find_temp_files(REPO)
    temp_total = sum(s for _, s in temps)
    print(f"   Found {len(temps)} temp/log files ({temp_total/1024/1024:.1f} MB)")
    if temps:
        # Show top 10 by size
        temps.sort(key=lambda x: x[1], reverse=True)
        for path, size in temps[:10]:
            print(f"   {size/1024:.0f} KB — {path}")
    
    # 4. Check disk space
    total_freed = cache_bytes + pyc_bytes
    print(f"\n{'='*60}")
    print(f"TOTAL FREED: {total_freed/1024/1024:.1f} MB")
    print(f"{'='*60}")
    
    # Get current C:\ free space
    try:
        usage = shutil.disk_usage("C:\\")
        print(f"C:\\ Free: {usage.free/1024/1024/1024:.1f} GB / {usage.total/1024/1024/1024:.1f} GB")
    except:
        pass
    
    # Write detailed log
    log_path = REPO / "logs" / "pycache_purge_log.txt"
    log_path.parent.mkdir(exist_ok=True)
    with open(log_path, "w") as f:
        f.write(f"__pycache__ purge log — {datetime.now().isoformat()}\n")
        f.write(f"Dirs removed: {dirs}\n")
        f.write(f"Orphan .pyc removed: {pyc_files}\n")
        f.write(f"Total freed: {total_freed/1024/1024:.1f} MB\n\n")
        for line in LOG:
            f.write(line + "\n")
    print(f"\nDetailed log: {log_path}")

if __name__ == "__main__":
    main()
