#!/usr/bin/env python3
"""
CASE DATABASE BUILDER & COURT DOCUMENT GENERATOR
=================================================
Production-grade tool for building per-case litigation databases from
analysis_engine.py output and generating Michigan court documents.

Plaintiff: Andrew J. Pigors (Pro Se)
Lane A: 2024-001507-DC — Custody (Judge McNeill, 14th Circuit Muskegon County)
Lane B: 2023-5907-PP   — Housing/PPO (Judge Hoopes, 14th Circuit)
Lane C: 2025-002760-CZ — Civil Rights/Convergence

Usage:
    python case_database_builder.py build                           # Build all 3 case databases
    python case_database_builder.py build --lane A                  # Build Lane A only
    python case_database_builder.py generate                        # Generate all court documents
    python case_database_builder.py generate --type motion_disqualify --lane A
    python case_database_builder.py report                          # Case status report
    python case_database_builder.py all                             # Everything

DISCLAIMER: Documents generated by this system are drafts for review.
All filings MUST be verified against current Michigan Court Rules before submission.
"""

import argparse
import json
import logging
import os
import re
import sqlite3
import sys
import textwrap
from datetime import datetime, date
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ════════════════════════════════════════════════════════════════════════════════
#  PATH CONFIGURATION
# ════════════════════════════════════════════════════════════════════════════════

LITIGATION_ROOT = Path(r"C:\Users\andre\LitigationOS")
SYSTEM_DIR = LITIGATION_ROOT / "00_SYSTEM"
MANIFESTS_DIR = SYSTEM_DIR / "manifests"
CASE_DB_DIR = LITIGATION_ROOT / "06_CASE_DATABASES"
COURT_DOC_DIR = LITIGATION_ROOT / "07_COURT_DOCUMENTS"

SOURCE_DB = MANIFESTS_DIR / "case_analysis.db"

# ════════════════════════════════════════════════════════════════════════════════
#  OPTIONAL IMPORTS — graceful fallback if modules not yet built
# ════════════════════════════════════════════════════════════════════════════════

try:
    sys.path.insert(0, str(SYSTEM_DIR / "legal_knowledge"))
    from michigan_court_rules import DOCUMENT_FORMATS, FILING_REQUIREMENTS
except ImportError:
    DOCUMENT_FORMATS = {}
    FILING_REQUIREMENTS = {}

try:
    sys.path.insert(0, str(SYSTEM_DIR / "pipeline"))
    from local_ai_engine import LocalAI
except ImportError:
    LocalAI = None

# ════════════════════════════════════════════════════════════════════════════════
#  LOGGING
# ════════════════════════════════════════════════════════════════════════════════

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("CaseDBBuilder")

# ════════════════════════════════════════════════════════════════════════════════
#  CASE LANE DEFINITIONS
# ════════════════════════════════════════════════════════════════════════════════

LANES: Dict[str, Dict[str, Any]] = {
    "A": {
        "case_number": "2024-001507-DC",
        "case_name": "Pigors v. Watson",
        "db_file": "lane_A_custody.db",
        "court": "14th Circuit Court",
        "county": "Muskegon",
        "judge": "Hon. Matthew McNeill",
        "case_type": "Custody / Domestic",
        "plaintiff": "ANDREW J. PIGORS",
        "defendant": "AMBER WATSON",
        "plaintiff_address": "Pro Se Litigant",
        "exhibit_prefix": "A",
        "doc_subdir": "lane_A",
        "lane_keys": ["A", "custody", "watson", "mcneill", "2024-001507-DC"],
        "court_level": "CIRCUIT",
        "state_header": "STATE OF MICHIGAN",
        "court_header": "IN THE CIRCUIT COURT FOR THE COUNTY OF MUSKEGON",
        "division": "DOMESTIC RELATIONS DIVISION",
    },
    "B": {
        "case_number": "2023-5907-PP",
        "case_name": "Pigors v. Shady Oaks et al.",
        "db_file": "lane_B_housing.db",
        "court": "14th Circuit Court",
        "county": "Muskegon",
        "judge": "Hon. Annette Hoopes",
        "case_type": "Housing / PPO",
        "plaintiff": "ANDREW J. PIGORS",
        "defendant": "SHADY OAKS MOBILE HOME PARK, et al.",
        "plaintiff_address": "Pro Se Litigant",
        "exhibit_prefix": "B",
        "doc_subdir": "lane_B",
        "lane_keys": ["B", "housing", "shady oaks", "hoopes", "2023-5907-PP"],
        "court_level": "CIRCUIT",
        "state_header": "STATE OF MICHIGAN",
        "court_header": "IN THE CIRCUIT COURT FOR THE COUNTY OF MUSKEGON",
        "division": "CIVIL DIVISION",
    },
    "C": {
        "case_number": "2025-002760-CZ",
        "case_name": "Pigors v. County of Muskegon et al.",
        "db_file": "lane_C_convergence.db",
        "court": "14th Circuit Court",
        "county": "Muskegon",
        "judge": "TBD",
        "case_type": "Civil Rights / Convergence",
        "plaintiff": "ANDREW J. PIGORS",
        "defendant": "COUNTY OF MUSKEGON, et al.",
        "plaintiff_address": "Pro Se Litigant",
        "exhibit_prefix": "C",
        "doc_subdir": "lane_C",
        "lane_keys": ["C", "convergence", "civil rights", "1983", "2025-002760-CZ"],
        "court_level": "CIRCUIT",
        "state_header": "STATE OF MICHIGAN",
        "court_header": "IN THE CIRCUIT COURT FOR THE COUNTY OF MUSKEGON",
        "division": "CIVIL DIVISION",
    },
}

# ════════════════════════════════════════════════════════════════════════════════
#  PART 1: PER-CASE DATABASE BUILDER
# ════════════════════════════════════════════════════════════════════════════════

CASE_DB_SCHEMA = """
-- Core case information
CREATE TABLE IF NOT EXISTS case_info (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    key         TEXT UNIQUE NOT NULL,
    value       TEXT,
    updated_at  TEXT DEFAULT (datetime('now'))
);

-- Evidence items with exhibit numbering
CREATE TABLE IF NOT EXISTS evidence (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    exhibit_number  TEXT UNIQUE,
    source_file_id  INTEGER,
    finding_id      INTEGER,
    description     TEXT NOT NULL,
    evidence_type   TEXT,            -- documentary, testimonial, physical, digital
    finding_text    TEXT,
    source_path     TEXT,
    page_number     INTEGER,
    admissibility   INTEGER DEFAULT 0,  -- 0-100 score
    relevance       INTEGER DEFAULT 0,
    weight          INTEGER DEFAULT 0,
    authentication  TEXT DEFAULT 'pending',
    mre_basis       TEXT,            -- Michigan Rule of Evidence basis
    notes           TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Legal claims / causes of action
CREATE TABLE IF NOT EXISTS claims (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    claim_number    INTEGER,
    issue_id        INTEGER,         -- FK to source legal_issues
    claim_type      TEXT NOT NULL,    -- due_process, custody_interference, etc.
    description     TEXT NOT NULL,
    legal_basis     TEXT,            -- statute or rule
    strength_score  INTEGER DEFAULT 0,
    status          TEXT DEFAULT 'active',  -- active, withdrawn, dismissed, resolved
    supporting_evidence TEXT,        -- JSON list of exhibit numbers
    opposing_arguments  TEXT,
    notes           TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Case timeline
CREATE TABLE IF NOT EXISTS timeline (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    event_date      TEXT,
    event_type      TEXT,            -- filing, hearing, incident, order, deadline
    description     TEXT NOT NULL,
    source_exhibit  TEXT,            -- exhibit number reference
    finding_id      INTEGER,
    significance    TEXT,            -- critical, important, background
    verified        BOOLEAN DEFAULT 0,
    notes           TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Witnesses and key persons
CREATE TABLE IF NOT EXISTS witnesses (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_id       INTEGER,
    name            TEXT NOT NULL,
    role            TEXT,            -- plaintiff, defendant, judge, witness, attorney, expert
    entity_type     TEXT,            -- person, organization, government
    affiliation     TEXT,
    relevance       TEXT,            -- which claims they relate to
    testimony_summary TEXT,
    contact_info    TEXT,
    deposition_status TEXT DEFAULT 'not_scheduled',
    notes           TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Legal authorities (statutes, rules, case law)
CREATE TABLE IF NOT EXISTS authorities (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    citation_id     INTEGER,
    citation_text   TEXT NOT NULL,
    citation_type   TEXT,            -- MCL, MCR, USC, case_law, MRE, constitution
    rule_number     TEXT,
    full_text       TEXT,
    relevance       TEXT,            -- which claims it supports
    favorable       BOOLEAN DEFAULT 1,  -- 1=supports our position, 0=adverse
    key_holding     TEXT,
    notes           TEXT,
    verified        BOOLEAN DEFAULT 0,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Opposition analysis
CREATE TABLE IF NOT EXISTS opposition_analysis (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    party           TEXT NOT NULL,
    argument        TEXT,
    weakness        TEXT,
    counter_argument TEXT,
    evidence_gap    TEXT,
    risk_level      TEXT DEFAULT 'medium',  -- low, medium, high, critical
    strategy_note   TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Damages calculation
CREATE TABLE IF NOT EXISTS damages (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    damage_type     TEXT NOT NULL,    -- compensatory, punitive, statutory, equitable
    category        TEXT,            -- economic, non-economic, injunctive
    description     TEXT NOT NULL,
    amount          REAL,
    calculation     TEXT,
    supporting_exhibit TEXT,
    legal_basis     TEXT,
    notes           TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Filings tracker
CREATE TABLE IF NOT EXISTS filings (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    filing_type     TEXT NOT NULL,    -- motion, brief, affidavit, complaint, order, notice
    title           TEXT NOT NULL,
    file_path       TEXT,
    filed_date      TEXT,
    due_date        TEXT,
    status          TEXT DEFAULT 'draft',  -- draft, ready, filed, served, pending_response
    response_deadline TEXT,
    judge_ruling    TEXT,
    notes           TEXT,
    created_at      TEXT DEFAULT (datetime('now'))
);

-- Action items / task tracker
CREATE TABLE IF NOT EXISTS action_items (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    priority        INTEGER DEFAULT 3,  -- 1=urgent, 2=high, 3=normal, 4=low
    category        TEXT,            -- filing, research, evidence, discovery, hearing_prep
    description     TEXT NOT NULL,
    deadline        TEXT,
    status          TEXT DEFAULT 'pending',  -- pending, in_progress, done, blocked
    depends_on      TEXT,            -- JSON list of action_item IDs
    assigned_to     TEXT DEFAULT 'pro_se',
    notes           TEXT,
    created_at      TEXT DEFAULT (datetime('now')),
    completed_at    TEXT
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_evidence_exhibit ON evidence(exhibit_number);
CREATE INDEX IF NOT EXISTS idx_claims_type ON claims(claim_type);
CREATE INDEX IF NOT EXISTS idx_timeline_date ON timeline(event_date);
CREATE INDEX IF NOT EXISTS idx_authorities_type ON authorities(citation_type);
CREATE INDEX IF NOT EXISTS idx_filings_status ON filings(status);
CREATE INDEX IF NOT EXISTS idx_action_items_priority ON action_items(priority, status);
"""


class CaseDatabaseBuilder:
    """Builds per-case SQLite databases from the central case_analysis.db."""

    def __init__(self):
        self.source_conn: Optional[sqlite3.Connection] = None
        self.ai = LocalAI() if LocalAI else None
        self._exhibit_counters: Dict[str, int] = {}

    def _open_source(self) -> sqlite3.Connection:
        """Open the source analysis database."""
        if not SOURCE_DB.exists():
            log.warning(f"Source DB not found: {SOURCE_DB}")
            log.info("Creating empty source DB structure for forward compatibility")
            conn = sqlite3.connect(str(SOURCE_DB))
            conn.row_factory = sqlite3.Row
            return conn
        conn = sqlite3.connect(str(SOURCE_DB))
        conn.row_factory = sqlite3.Row
        return conn

    def _open_case_db(self, lane: str) -> sqlite3.Connection:
        """Open (or create) a per-case database."""
        cfg = LANES[lane]
        db_path = CASE_DB_DIR / cfg["db_file"]
        CASE_DB_DIR.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        conn.executescript(CASE_DB_SCHEMA)
        conn.commit()
        log.info(f"Case DB ready: {db_path}")
        return conn

    def _next_exhibit(self, lane: str) -> str:
        """Generate the next exhibit number for a lane (e.g., A-001)."""
        prefix = LANES[lane]["exhibit_prefix"]
        count = self._exhibit_counters.get(lane, 0) + 1
        self._exhibit_counters[lane] = count
        return f"{prefix}-{count:03d}"

    def _determine_lane(self, row: sqlite3.Row, target_lane: str) -> bool:
        """Check whether a source row belongs to the target lane."""
        case_lane = row["case_lane"] if "case_lane" in row.keys() else None
        if not case_lane:
            return True  # If no lane assigned, include in all
        lane_val = str(case_lane).strip().upper()
        if lane_val == target_lane:
            return True
        cfg = LANES[target_lane]
        for key in cfg["lane_keys"]:
            if key.lower() in str(case_lane).lower():
                return True
        return False

    def _populate_case_info(self, conn: sqlite3.Connection, lane: str):
        """Insert core case metadata."""
        cfg = LANES[lane]
        info_pairs = [
            ("case_number", cfg["case_number"]),
            ("case_name", cfg["case_name"]),
            ("court", cfg["court"]),
            ("county", cfg["county"]),
            ("judge", cfg["judge"]),
            ("case_type", cfg["case_type"]),
            ("plaintiff", cfg["plaintiff"]),
            ("defendant", cfg["defendant"]),
            ("exhibit_prefix", cfg["exhibit_prefix"]),
            ("lane", lane),
            ("court_level", cfg["court_level"]),
            ("division", cfg["division"]),
            ("plaintiff_status", "Pro Se"),
            ("build_timestamp", datetime.now().isoformat()),
        ]
        for key, value in info_pairs:
            conn.execute(
                "INSERT OR REPLACE INTO case_info (key, value, updated_at) VALUES (?, ?, datetime('now'))",
                (key, value),
            )
        conn.commit()
        log.info(f"  Lane {lane}: case_info populated ({len(info_pairs)} entries)")

    def _populate_evidence(self, src: sqlite3.Connection, dst: sqlite3.Connection, lane: str):
        """Map factual_findings → evidence table with exhibit numbers."""
        rows = src.execute(
            "SELECT ff.*, af.path as source_path FROM factual_findings ff "
            "LEFT JOIN analyzed_files af ON ff.file_id = af.id"
        ).fetchall()

        count = 0
        for row in rows:
            if not self._determine_lane(row, lane):
                continue
            exhibit = self._next_exhibit(lane)
            dst.execute(
                "INSERT INTO evidence "
                "(exhibit_number, source_file_id, finding_id, description, evidence_type, "
                "finding_text, source_path, page_number, admissibility, relevance, weight, "
                "authentication, notes) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    exhibit,
                    row["file_id"],
                    row["id"],
                    row["finding_text"][:200] if row["finding_text"] else "Finding",
                    row["finding_type"] or "documentary",
                    row["finding_text"],
                    row["source_path"] if "source_path" in row.keys() else None,
                    row["page_number"],
                    row["admissibility_score"] or 0,
                    row["relevance_score"] or 0,
                    row["weight_score"] or 0,
                    row["authentication_level"] or "pending",
                    f"Auto-imported from analysis. Context: {(row['context'] or '')[:100]}",
                ),
            )
            count += 1
        dst.commit()
        log.info(f"  Lane {lane}: {count} evidence items imported")

    def _populate_claims(self, src: sqlite3.Connection, dst: sqlite3.Connection, lane: str):
        """Map legal_issues → claims table."""
        rows = src.execute("SELECT * FROM legal_issues").fetchall()
        count = 0
        claim_num = 0
        for row in rows:
            if not self._determine_lane(row, lane):
                continue
            claim_num += 1

            # Gather supporting evidence from evidence_chain
            chain_rows = src.execute(
                "SELECT finding_id, strength, explanation FROM evidence_chain "
                "WHERE supports_issue_id = ?",
                (row["id"],),
            ).fetchall()
            supporting = json.dumps([
                {"finding_id": c["finding_id"], "strength": c["strength"]}
                for c in chain_rows
            ]) if chain_rows else "[]"

            dst.execute(
                "INSERT INTO claims "
                "(claim_number, issue_id, claim_type, description, legal_basis, "
                "strength_score, supporting_evidence, notes) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    claim_num,
                    row["id"],
                    row["issue_type"] or "general",
                    row["description"] or row["supporting_text"] or "Legal issue",
                    row["supporting_text"],
                    row["strength_score"] or 0,
                    supporting,
                    f"Auto-imported. Source page: {row['page_number']}",
                ),
            )
            count += 1
        dst.commit()
        log.info(f"  Lane {lane}: {count} claims imported")

    def _populate_timeline(self, src: sqlite3.Connection, dst: sqlite3.Connection, lane: str):
        """Map factual_findings with date patterns → timeline entries."""
        date_re = re.compile(
            r'(\d{4}-\d{2}-\d{2})|'
            r'(\d{1,2}/\d{1,2}/\d{4})|'
            r'((?:January|February|March|April|May|June|July|August|September|'
            r'October|November|December)\s+\d{1,2},?\s+\d{4})',
            re.IGNORECASE,
        )
        rows = src.execute("SELECT * FROM factual_findings").fetchall()
        count = 0
        for row in rows:
            if not self._determine_lane(row, lane):
                continue
            text = row["finding_text"] or ""
            match = date_re.search(text)
            event_date = None
            if match:
                raw = match.group(0)
                event_date = self._normalize_date(raw)

            if event_date or (row["finding_type"] and "date" in str(row["finding_type"]).lower()):
                significance = "background"
                if (row["relevance_score"] or 0) >= 70:
                    significance = "critical"
                elif (row["relevance_score"] or 0) >= 40:
                    significance = "important"

                dst.execute(
                    "INSERT INTO timeline "
                    "(event_date, event_type, description, finding_id, significance, notes) "
                    "VALUES (?, ?, ?, ?, ?, ?)",
                    (
                        event_date,
                        row["finding_type"] or "event",
                        text[:500],
                        row["id"],
                        significance,
                        row["context"][:200] if row["context"] else None,
                    ),
                )
                count += 1
        dst.commit()
        log.info(f"  Lane {lane}: {count} timeline entries imported")

    def _populate_witnesses(self, src: sqlite3.Connection, dst: sqlite3.Connection, lane: str):
        """Map entities → witnesses table."""
        rows = src.execute("SELECT * FROM entities").fetchall()
        count = 0
        for row in rows:
            # Check lane association
            case_lanes = row["case_lanes"] or ""
            if lane not in case_lanes.upper() and case_lanes.strip():
                # Check lane keys
                matched = False
                for key in LANES[lane]["lane_keys"]:
                    if key.lower() in case_lanes.lower():
                        matched = True
                        break
                if not matched and case_lanes.strip():
                    continue

            dst.execute(
                "INSERT INTO witnesses "
                "(entity_id, name, role, entity_type, notes) "
                "VALUES (?, ?, ?, ?, ?)",
                (
                    row["id"],
                    row["entity_name"] or row["normalized_name"],
                    row["role"] or "unknown",
                    row["entity_type"] or "person",
                    f"Mentions: {row['mention_count']}. Lanes: {case_lanes}",
                ),
            )
            count += 1
        dst.commit()
        log.info(f"  Lane {lane}: {count} witnesses imported")

    def _populate_authorities(self, src: sqlite3.Connection, dst: sqlite3.Connection, lane: str):
        """Map citations → authorities table."""
        rows = src.execute("SELECT * FROM citations").fetchall()
        count = 0
        for row in rows:
            if not self._determine_lane(row, lane):
                continue
            dst.execute(
                "INSERT INTO authorities "
                "(citation_id, citation_text, citation_type, rule_number, "
                "full_text, notes, verified) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    row["id"],
                    row["citation_text"],
                    row["citation_type"],
                    row["rule_number"],
                    row["context"],
                    f"Page {row['page_number']}, Line {row['line_number']}",
                    row["verified"] if row["verified"] is not None else 0,
                ),
            )
            count += 1
        dst.commit()
        log.info(f"  Lane {lane}: {count} authorities imported")

    def _populate_summary_actions(self, src: sqlite3.Connection, dst: sqlite3.Connection, lane: str):
        """Generate action items from analysis_summary recommendations."""
        rows = src.execute(
            "SELECT * FROM analysis_summary WHERE case_lane = ?", (lane,)
        ).fetchall()
        for row in rows:
            actions_raw = row["recommended_actions"] or ""
            for i, action in enumerate(actions_raw.split(";"), 1):
                action = action.strip()
                if not action:
                    continue
                dst.execute(
                    "INSERT INTO action_items (priority, category, description) VALUES (?, ?, ?)",
                    (2, "research", action),
                )

            weakest = row["weakest_areas"] or ""
            for area in weakest.split(";"):
                area = area.strip()
                if not area:
                    continue
                dst.execute(
                    "INSERT INTO action_items (priority, category, description) VALUES (?, ?, ?)",
                    (1, "evidence", f"Address weakness: {area}"),
                )
        dst.commit()

    @staticmethod
    def _normalize_date(raw: str) -> Optional[str]:
        """Attempt to normalize a date string to ISO format."""
        from datetime import datetime as dt
        for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%B %d, %Y", "%B %d %Y"):
            try:
                return dt.strptime(raw.strip().replace(",", ", ").replace("  ", " "), fmt).strftime("%Y-%m-%d")
            except ValueError:
                continue
        return raw

    def build_lane(self, lane: str):
        """Build the complete per-case database for one lane."""
        if lane not in LANES:
            log.error(f"Unknown lane: {lane}. Valid lanes: {list(LANES.keys())}")
            return
        log.info(f"═══ Building Lane {lane}: {LANES[lane]['case_name']} ═══")

        src = self._open_source()
        dst = self._open_case_db(lane)

        try:
            self._populate_case_info(dst, lane)
            self._populate_evidence(src, dst, lane)
            self._populate_claims(src, dst, lane)
            self._populate_timeline(src, dst, lane)
            self._populate_witnesses(src, dst, lane)
            self._populate_authorities(src, dst, lane)
            self._populate_summary_actions(src, dst, lane)
            log.info(f"═══ Lane {lane} build complete ═══\n")
        finally:
            src.close()
            dst.close()

    def build_all(self):
        """Build databases for all three lanes."""
        log.info("Building all case databases...")
        for lane in LANES:
            self.build_lane(lane)
        log.info("All case databases built successfully.")


# ════════════════════════════════════════════════════════════════════════════════
#  PART 2: COURT DOCUMENT GENERATOR
# ════════════════════════════════════════════════════════════════════════════════

class CourtDocumentGenerator:
    """Generates properly formatted Michigan court documents from case databases."""

    TODAY = date.today().strftime("%B %d, %Y")
    TODAY_ISO = date.today().isoformat()

    # ── Document registry ────────────────────────────────────────────────
    DOCUMENT_TYPES = {
        "motion_summary_disposition": {
            "title": "MOTION FOR SUMMARY DISPOSITION",
            "mcr": "MCR 2.116",
            "filename": "motion_summary_disposition.txt",
            "subdir": "motions",
            "needs_brief": True,
            "needs_proposed_order": True,
        },
        "motion_disqualify": {
            "title": "MOTION TO DISQUALIFY JUDGE",
            "mcr": "MCR 2.003",
            "filename": "motion_disqualify_judge.txt",
            "subdir": "motions",
            "needs_affidavit": True,
            "needs_proposed_order": True,
        },
        "motion_parenting_time": {
            "title": "EMERGENCY MOTION FOR PARENTING TIME",
            "mcr": "MCR 3.206",
            "filename": "emergency_motion_parenting_time.txt",
            "subdir": "motions",
            "needs_affidavit": True,
            "needs_proposed_order": True,
        },
        "brief_in_support": {
            "title": "BRIEF IN SUPPORT OF MOTION",
            "mcr": "MCR 2.119",
            "filename": "brief_in_support.txt",
            "subdir": "briefs",
        },
        "affidavit": {
            "title": "AFFIDAVIT OF ANDREW J. PIGORS",
            "mcr": "MCR 2.119(B)",
            "filename": "affidavit_pigors.txt",
            "subdir": "affidavits",
        },
        "jtc_complaint": {
            "title": "FORMAL COMPLAINT — JUDICIAL TENURE COMMISSION",
            "mcr": "MCR 9.200 et seq.",
            "filename": "jtc_formal_complaint.txt",
            "subdir": "complaints",
        },
        "coa_leave_application": {
            "title": "APPLICATION FOR LEAVE TO APPEAL",
            "mcr": "MCR 7.205",
            "filename": "coa_application_leave.txt",
            "subdir": "appeals",
        },
        "complaint_1983": {
            "title": "COMPLAINT UNDER 42 U.S.C. § 1983",
            "mcr": "42 USC § 1983; Fed. R. Civ. P. 8",
            "filename": "complaint_42usc1983.txt",
            "subdir": "complaints",
        },
        "proposed_order": {
            "title": "PROPOSED ORDER",
            "mcr": "MCR 2.602",
            "filename": "proposed_order.txt",
            "subdir": "orders",
        },
        "certificate_of_service": {
            "title": "CERTIFICATE OF SERVICE",
            "mcr": "MCR 2.107",
            "filename": "certificate_of_service.txt",
            "subdir": "service",
        },
    }

    def __init__(self):
        self.ai = LocalAI() if LocalAI else None

    def _open_case_db(self, lane: str) -> Optional[sqlite3.Connection]:
        """Open a per-case database for reading."""
        cfg = LANES[lane]
        db_path = CASE_DB_DIR / cfg["db_file"]
        if not db_path.exists():
            log.warning(f"Case DB not found for Lane {lane}: {db_path}")
            log.info("Run 'build' first, or proceeding with template defaults.")
            return None
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        return conn

    def _get_case_info(self, conn: Optional[sqlite3.Connection], lane: str) -> Dict[str, str]:
        """Retrieve case_info key-value pairs, falling back to LANES config."""
        cfg = LANES[lane]
        info = {
            "case_number": cfg["case_number"],
            "case_name": cfg["case_name"],
            "court": cfg["court"],
            "county": cfg["county"],
            "judge": cfg["judge"],
            "plaintiff": cfg["plaintiff"],
            "defendant": cfg["defendant"],
            "division": cfg["division"],
            "state_header": cfg["state_header"],
            "court_header": cfg["court_header"],
        }
        if conn:
            try:
                rows = conn.execute("SELECT key, value FROM case_info").fetchall()
                for row in rows:
                    info[row["key"]] = row["value"]
            except Exception:
                pass
        return info

    def _get_evidence(self, conn: Optional[sqlite3.Connection], limit: int = 20) -> List[Dict]:
        """Retrieve top evidence from case DB."""
        if not conn:
            return []
        try:
            rows = conn.execute(
                "SELECT * FROM evidence ORDER BY relevance DESC, admissibility DESC LIMIT ?",
                (limit,),
            ).fetchall()
            return [dict(r) for r in rows]
        except Exception:
            return []

    def _get_claims(self, conn: Optional[sqlite3.Connection]) -> List[Dict]:
        """Retrieve claims from case DB."""
        if not conn:
            return []
        try:
            rows = conn.execute(
                "SELECT * FROM claims WHERE status = 'active' ORDER BY strength_score DESC"
            ).fetchall()
            return [dict(r) for r in rows]
        except Exception:
            return []

    def _get_authorities(self, conn: Optional[sqlite3.Connection], favorable: bool = True) -> List[Dict]:
        """Retrieve authorities from case DB."""
        if not conn:
            return []
        try:
            rows = conn.execute(
                "SELECT * FROM authorities WHERE favorable = ? ORDER BY citation_type",
                (1 if favorable else 0,),
            ).fetchall()
            return [dict(r) for r in rows]
        except Exception:
            return []

    def _get_witnesses(self, conn: Optional[sqlite3.Connection]) -> List[Dict]:
        """Retrieve witnesses from case DB."""
        if not conn:
            return []
        try:
            rows = conn.execute("SELECT * FROM witnesses ORDER BY role, name").fetchall()
            return [dict(r) for r in rows]
        except Exception:
            return []

    def _get_timeline(self, conn: Optional[sqlite3.Connection], limit: int = 30) -> List[Dict]:
        """Retrieve timeline from case DB."""
        if not conn:
            return []
        try:
            rows = conn.execute(
                "SELECT * FROM timeline ORDER BY event_date ASC LIMIT ?", (limit,)
            ).fetchall()
            return [dict(r) for r in rows]
        except Exception:
            return []

    # ── Caption / Header Formatting ──────────────────────────────────────

    def _build_caption(self, info: Dict, doc_title: str, mcr: str = "") -> str:
        """Generate a proper Michigan court caption."""
        width = 72
        divider = "=" * width

        caption = f"""{info['state_header'].center(width)}

{info['court_header'].center(width)}
{info.get('division', '').center(width)}

{info['plaintiff']},
    Plaintiff (Pro Se),                Case No. {info['case_number']}

        v.                             {f'Hon. {info["judge"].replace("Hon. ", "")}' if not info['judge'].startswith('Hon.') else info['judge']}

{info['defendant']},
    Defendant(s).
{divider}
ANDREW J. PIGORS (Pro Se)
[Address]
[City, State ZIP]
[Phone]
[Email]
{divider}

{doc_title.center(width)}
{f'({mcr})'.center(width) if mcr else ''}
"""
        return caption

    def _build_certificate_of_service(self, info: Dict) -> str:
        """Generate Certificate of Service block."""
        return f"""
CERTIFICATE OF SERVICE

    I, Andrew J. Pigors, hereby certify that on {self.TODAY}, I served a
true and correct copy of the foregoing document upon all parties and/or their
attorneys of record by:

    [X] First-class U.S. Mail, postage prepaid
    [ ] Personal delivery
    [ ] Electronic filing (MiFILE)
    [ ] Email (with consent of recipient)

to the following:

    {info['defendant']}
    c/o [Attorney Name / Address]
    [City, State ZIP]

    [Additional parties as applicable]


                                    ________________________________________
                                    ANDREW J. PIGORS, Pro Se Plaintiff
                                    Dated: {self.TODAY}
"""

    def _build_verification(self) -> str:
        """Generate verification/affidavit jurat."""
        return f"""
VERIFICATION

STATE OF MICHIGAN   )
                    ) ss.
COUNTY OF MUSKEGON  )

    I, Andrew J. Pigors, being first duly sworn, depose and state that I have
read the foregoing document and that the facts stated therein are true to the
best of my knowledge, information, and belief.


                                    ________________________________________
                                    ANDREW J. PIGORS

Subscribed and sworn to before me
this _____ day of _____________, {date.today().year}.

________________________________________
Notary Public, State of Michigan
County of Muskegon
My commission expires: ______________
"""

    # ── Document Generators ──────────────────────────────────────────────

    def _gen_motion_summary_disposition(self, lane: str, conn, info: Dict) -> str:
        """MCR 2.116 — Motion for Summary Disposition."""
        claims = self._get_claims(conn)
        evidence = self._get_evidence(conn)
        authorities = self._get_authorities(conn)

        claims_text = ""
        for i, c in enumerate(claims[:10], 1):
            claims_text += f"    {i}. {c['claim_type'].replace('_', ' ').title()}: {c['description'][:200]}\n"
        if not claims_text:
            claims_text = "    [Claims to be inserted from case database]\n"

        evidence_text = ""
        for e in evidence[:10]:
            evidence_text += f"    - Exhibit {e['exhibit_number']}: {e['description'][:150]}\n"
        if not evidence_text:
            evidence_text = "    [Evidence references to be inserted]\n"

        authority_text = ""
        for a in authorities[:10]:
            authority_text += f"    - {a['citation_text']}\n"
        if not authority_text:
            authority_text = "    - MCR 2.116(C)(10)\n    - MCR 2.116(I)(2)\n"

        doc = self._build_caption(info, "MOTION FOR SUMMARY DISPOSITION", "MCR 2.116")
        doc += f"""
    NOW COMES Plaintiff, Andrew J. Pigors, appearing pro se, and pursuant
to MCR 2.116(C)(10), respectfully moves this Honorable Court for an Order
granting summary disposition in Plaintiff's favor and against Defendant(s),
and in support thereof states as follows:

I. INTRODUCTION

    1. This Motion is brought pursuant to MCR 2.116(C)(10), which provides
that summary disposition is appropriate where "[e]xcept as to the amount of
damages, there is no genuine issue as to any material fact, and the moving
party is entitled to judgment or partial judgment as a matter of law."

    2. The undisputed material facts and applicable law demonstrate that
Plaintiff is entitled to judgment as a matter of law on the claims set
forth below.

II. STATEMENT OF UNDISPUTED MATERIAL FACTS

    3. Plaintiff incorporates by reference the Affidavit of Andrew J. Pigors
and all exhibits attached thereto.

    4. The following material facts are supported by admissible evidence and
are not subject to genuine dispute:

{evidence_text}

III. CLAIMS AT ISSUE

{claims_text}

IV. LEGAL STANDARD

    5. Under MCR 2.116(C)(10), a motion for summary disposition tests
whether there is factual support for a claim. The moving party must
specifically identify the issues for which there is no genuine issue of
material fact. Quinto v. Cross & Peters Co., 451 Mich 358, 362 (1996).

    6. Once the moving party meets this burden, the opposing party must
demonstrate by admissible evidence that a genuine issue of disputed fact
exists. MCR 2.116(G)(4).

V. ARGUMENT

    7. The undisputed facts establish each element of Plaintiff's claims:

{claims_text}

    8. The following authorities support Plaintiff's position:

{authority_text}

    9. Defendant(s) cannot establish a genuine issue of material fact
sufficient to overcome this Motion.

VI. RELIEF REQUESTED

    WHEREFORE, Plaintiff respectfully requests that this Honorable Court:

    a. Grant summary disposition in Plaintiff's favor pursuant to
       MCR 2.116(C)(10);
    b. Enter judgment against Defendant(s) on all claims;
    c. Award damages as proven at trial or by affidavit;
    d. Award costs and such other relief as the Court deems just and proper.

Respectfully submitted,


________________________________________
ANDREW J. PIGORS, Pro Se Plaintiff
Dated: {self.TODAY}
"""
        doc += self._build_certificate_of_service(info)
        return doc

    def _gen_motion_disqualify(self, lane: str, conn, info: Dict) -> str:
        """MCR 2.003 — Motion to Disqualify Judge."""
        evidence = self._get_evidence(conn)
        timeline = self._get_timeline(conn)

        bias_evidence = ""
        for e in evidence[:8]:
            desc = e['description'][:150] if isinstance(e, dict) else str(e)[:150]
            bias_evidence += f"    - {desc}\n"
        if not bias_evidence:
            bias_evidence = "    [Specific instances of bias to be documented]\n"

        doc = self._build_caption(info, "MOTION TO DISQUALIFY JUDGE", "MCR 2.003")
        doc += f"""
    NOW COMES Plaintiff, Andrew J. Pigors, appearing pro se, and pursuant
to MCR 2.003, respectfully moves this Honorable Court for disqualification
of {info['judge']} from further proceedings in this matter, and in support
thereof states as follows:

I. LEGAL STANDARD

    1. MCR 2.003(C)(1) provides that a judge is disqualified when the judge
is biased or prejudiced for or against a party or attorney.

    2. MCR 2.003(C)(1)(a) provides for disqualification where the judge has
a personal bias or prejudice concerning a party.

    3. MCR 2.003(C)(1)(b) provides for disqualification where the judge has
personal knowledge of disputed evidentiary facts concerning the proceeding.

    4. The test is whether a reasonable person, knowing all the circumstances,
would conclude that the judge's impartiality might reasonably be questioned.
In re MCI Telecom Complaint, 460 Mich 396, 411 (1999).

II. STATEMENT OF FACTS SUPPORTING DISQUALIFICATION

    5. The following facts demonstrate that {info['judge']}'s impartiality
may reasonably be questioned:

{bias_evidence}

    6. A pattern of conduct by the assigned judge demonstrates actual bias
or, at minimum, the appearance of impropriety:

    a. [Specific ruling or statement demonstrating bias - DATE]
    b. [Specific procedural irregularity - DATE]
    c. [Ex parte communication or improper contact - DATE]
    d. [Disparate treatment of pro se litigant - DATE]

III. ARGUMENT

    7. The cumulative pattern of judicial conduct in this case rises to the
level requiring disqualification under MCR 2.003. A reasonable, objective
person would harbor a serious doubt about the judge's impartiality.

    8. Disqualification is not a matter of the judge's subjective view of
their own impartiality, but an objective standard viewed from the
perspective of a reasonable person fully informed of the circumstances.
Cain v. Michigan Dep't of Corrections, 451 Mich 470, 497 (1996).

    9. The Michigan Code of Judicial Conduct, Canon 2, requires that a
judge shall avoid impropriety and the appearance of impropriety in all
activities, and Canon 3(A)(4) states a judge shall be patient, dignified,
and courteous to litigants.

IV. RELIEF REQUESTED

    WHEREFORE, Plaintiff respectfully requests that:

    a. {info['judge']} be disqualified from further proceedings;
    b. This case be reassigned to another judge pursuant to MCR 2.003;
    c. All orders entered after the point at which disqualification should
       have occurred be reviewed by the successor judge.

Respectfully submitted,


________________________________________
ANDREW J. PIGORS, Pro Se Plaintiff
Dated: {self.TODAY}
"""
        doc += self._build_certificate_of_service(info)
        return doc

    def _gen_motion_parenting_time(self, lane: str, conn, info: Dict) -> str:
        """MCR 3.206 — Emergency Motion for Parenting Time."""
        evidence = self._get_evidence(conn)

        doc = self._build_caption(info, "EMERGENCY MOTION FOR PARENTING TIME", "MCR 3.206")
        doc += f"""
    NOW COMES Plaintiff, Andrew J. Pigors, appearing pro se, and pursuant
to MCR 3.206 and MCL 722.27a, respectfully moves this Honorable Court on
an emergency basis for an Order enforcing Plaintiff's parenting time rights,
and in support thereof states as follows:

I. GROUNDS FOR EMERGENCY RELIEF

    1. This motion is brought on an emergency basis because Plaintiff's
parenting time has been wrongfully denied/interfered with, causing
immediate and irreparable harm to both Plaintiff and the minor child(ren).

    2. MCL 722.27a(7) provides that a parenting time order is enforceable
by the court, and a parent who wrongfully denies parenting time may be
held in contempt.

    3. The Michigan Child Custody Act, MCL 722.23, establishes that it is
in the best interest of the child to have a strong relationship with both
parents, and MCL 722.27a establishes the right to reasonable parenting time.

II. STATEMENT OF FACTS

    4. Plaintiff is the father of [child's initials], born [DOB].

    5. An existing court order establishes Plaintiff's parenting time
schedule as follows: [describe current order].

    6. Defendant has wrongfully denied or interfered with Plaintiff's
parenting time on the following occasions:

    a. [Date]: [Description of denial/interference]
    b. [Date]: [Description of denial/interference]
    c. [Date]: [Description of denial/interference]

    7. Plaintiff has made good-faith efforts to resolve this matter
without court intervention, including: [describe efforts].

III. HARM TO CHILD

    8. The denial of parenting time is contrary to the child's best
interests as defined by MCL 722.23, because:

    a. The child has a close and bonded relationship with Plaintiff;
    b. Denial of parenting time disrupts the child's emotional stability;
    c. The child has expressed desire to maintain contact with Plaintiff;
    d. The ongoing denial constitutes parental alienation.

IV. LEGAL AUTHORITY

    9. MCL 722.27a — Parenting time; best interests of child.
    10. MCL 722.23 — Best interest factors.
    11. MCR 3.206 — Domestic Relations proceedings.
    12. MCL 722.31 — Change of domicile.
    13. Shade v. Wright, 291 Mich App 17 (2010) — parenting time enforcement.

V. RELIEF REQUESTED

    WHEREFORE, Plaintiff respectfully requests that this Court:

    a. Issue an emergency order restoring Plaintiff's parenting time;
    b. Find Defendant in contempt for wrongful denial of parenting time;
    c. Award Plaintiff make-up parenting time pursuant to MCL 722.27a(7)(c);
    d. Order Defendant to pay Plaintiff's costs and reasonable expenses;
    e. Modify the parenting time order to prevent future denials;
    f. Grant such other and further relief as the Court deems just.

Respectfully submitted,


________________________________________
ANDREW J. PIGORS, Pro Se Plaintiff
Dated: {self.TODAY}
"""
        doc += self._build_certificate_of_service(info)
        return doc

    def _gen_brief_in_support(self, lane: str, conn, info: Dict) -> str:
        """MCR 2.119 — Brief in Support of Motion."""
        claims = self._get_claims(conn)
        authorities = self._get_authorities(conn)
        evidence = self._get_evidence(conn)

        authority_block = ""
        for a in authorities[:15]:
            authority_block += f"    {a['citation_text']}\n"
        if not authority_block:
            authority_block = "    [Authorities to be inserted from case database]\n"

        argument_block = ""
        for i, c in enumerate(claims[:6], 1):
            argument_block += f"""
    {chr(64+i)}. {c['claim_type'].replace('_',' ').title()}

        {i + 2}. {c['description'][:300]}

        Strength of this claim: {c['strength_score']}/100.
"""
        if not argument_block:
            argument_block = "\n    [Detailed arguments to be developed]\n"

        doc = self._build_caption(info, "BRIEF IN SUPPORT OF MOTION", "MCR 2.119")
        doc += f"""
TABLE OF CONTENTS

    I.   Introduction ................................................ 1
    II.  Statement of Facts .......................................... 2
    III. Legal Standard .............................................. 3
    IV.  Argument .................................................... 4
    V.   Conclusion .................................................. 8

TABLE OF AUTHORITIES

Cases:
    [Case citations to be populated from authorities database]

Statutes and Rules:
{authority_block}

I. INTRODUCTION

    1. Plaintiff, Andrew J. Pigors, submits this Brief in Support of his
Motion filed in the above-captioned matter. This Brief demonstrates that
Plaintiff is entitled to the relief requested based on undisputed facts
and controlling legal authority.

II. STATEMENT OF FACTS

    2. The facts relevant to this Motion are established by the evidence
of record and the Affidavit of Andrew J. Pigors submitted herewith.

"""
        # Insert evidence references
        for e in evidence[:8]:
            doc += f"    - Exhibit {e['exhibit_number']}: {e['description'][:120]}\n"

        doc += f"""

III. LEGAL STANDARD

    [Standard applicable to the motion type — to be tailored per motion]

IV. ARGUMENT
{argument_block}

V. CONCLUSION

    For the foregoing reasons, Plaintiff respectfully requests that this
Honorable Court grant the relief requested in the accompanying Motion.

Respectfully submitted,


________________________________________
ANDREW J. PIGORS, Pro Se Plaintiff
Dated: {self.TODAY}
"""
        doc += self._build_certificate_of_service(info)
        return doc

    def _gen_affidavit(self, lane: str, conn, info: Dict) -> str:
        """MCR 2.119(B) — Affidavit of Andrew J. Pigors."""
        evidence = self._get_evidence(conn)
        timeline = self._get_timeline(conn)

        fact_block = ""
        for i, e in enumerate(evidence[:15], 4):
            fact_block += f"    {i}. {e['description'][:250]}\n\n"
        if not fact_block:
            fact_block = "    4. [Factual assertions to be inserted from evidence database]\n\n"

        timeline_block = ""
        for t in timeline[:10]:
            d = t['event_date'] or '[Date]'
            timeline_block += f"    - {d}: {t['description'][:150]}\n"
        if not timeline_block:
            timeline_block = "    [Timeline to be inserted]\n"

        doc = self._build_caption(info, "AFFIDAVIT OF ANDREW J. PIGORS", "MCR 2.119(B)")
        doc += f"""
STATE OF MICHIGAN   )
                    ) ss.
COUNTY OF MUSKEGON  )

    I, Andrew J. Pigors, being first duly sworn upon oath, depose and
state as follows:

    1. I am the Plaintiff in the above-captioned matter and I am over the
age of 18 years. I make this Affidavit based upon my personal knowledge
and, where indicated, upon information and belief.

    2. I am competent to testify to the matters stated herein. If called
as a witness, I could and would testify competently to the following facts.

    3. The following is a summary of relevant events:

{timeline_block}

SPECIFIC FACTUAL ASSERTIONS:

{fact_block}

EXHIBITS REFERENCED:

"""
        for e in evidence[:15]:
            doc += f"    Exhibit {e['exhibit_number']}: {e['description'][:100]}\n"

        doc += f"""

    I declare under the penalties of perjury under the laws of the State
of Michigan that the foregoing is true and correct to the best of my
knowledge, information, and belief.

    FURTHER AFFIANT SAYETH NOT.


                                    ________________________________________
                                    ANDREW J. PIGORS, Affiant

"""
        doc += self._build_verification()
        doc += self._build_certificate_of_service(info)
        return doc

    def _gen_jtc_complaint(self, lane: str, conn, info: Dict) -> str:
        """Judicial Tenure Commission Formal Complaint."""
        evidence = self._get_evidence(conn)
        timeline = self._get_timeline(conn)

        width = 72
        doc = f"""{'JUDICIAL TENURE COMMISSION'.center(width)}
{'STATE OF MICHIGAN'.center(width)}
{'3034 W. Grand Blvd., Suite 8-450'.center(width)}
{'Detroit, Michigan 48202'.center(width)}

{'=' * width}

{'FORMAL COMPLAINT'.center(width)}

{'=' * width}

COMPLAINANT:
    Andrew J. Pigors
    [Address]
    [City, State ZIP]
    [Phone]
    [Email]

RESPONDENT JUDGE:
    {info['judge']}
    {info['court']}
    {info['county']} County, Michigan

CASE REFERENCE:
    {info['case_number']} — {info['case_name']}

{'=' * width}

I. INTRODUCTION

    1. This Formal Complaint is submitted to the Judicial Tenure Commission
pursuant to MCR 9.200 et seq. and Const. 1963, Art. 6, § 30, regarding
the conduct of {info['judge']} in the above-referenced matter.

    2. The Complainant, Andrew J. Pigors, is a pro se litigant in the
above-referenced case and has personally witnessed and been subjected to
the judicial misconduct described herein.

II. JURISDICTION

    3. The Judicial Tenure Commission has jurisdiction over this complaint
pursuant to Const. 1963, Art. 6, § 30, which empowers the Commission to
investigate complaints against judges and to recommend discipline.

    4. MCR 9.207 provides that any person may file a complaint against a
judge with the Commission.

III. FACTUAL ALLEGATIONS

    5. The following specific instances of judicial misconduct have occurred
in the course of the above-referenced proceedings:

"""
        for i, e in enumerate(evidence[:10], 1):
            doc += f"    {chr(96+i)}) {e['description'][:200]}\n\n"

        if not evidence:
            doc += """    a) [Specific instance of misconduct — DATE, description]

    b) [Specific instance of misconduct — DATE, description]

    c) [Specific instance of misconduct — DATE, description]

"""

        doc += f"""
IV. VIOLATIONS OF THE MICHIGAN CODE OF JUDICIAL CONDUCT

    6. The conduct described above violates the following Canons of the
Michigan Code of Judicial Conduct:

    a. Canon 1: A judge should uphold the integrity and independence of
       the judiciary.

    b. Canon 2: A judge should avoid impropriety and the appearance of
       impropriety in all activities.

    c. Canon 3(A)(3): A judge should be patient, dignified, and courteous
       to litigants, jurors, witnesses, lawyers, and others with whom the
       judge deals in an official capacity.

    d. Canon 3(A)(4): A judge shall accord to every person who has a legal
       interest in a proceeding the right to be heard according to law.

V. PATTERN OF CONDUCT

    7. The misconduct described herein is not an isolated incident but
reflects a pattern of behavior that undermines public confidence in the
judiciary and causes actual prejudice to the Complainant's legal rights.

VI. RELIEF REQUESTED

    8. Complainant respectfully requests that the Judicial Tenure Commission:

    a. Investigate the conduct of {info['judge']} as described herein;
    b. Take appropriate disciplinary action;
    c. Recommend to the Michigan Supreme Court such sanctions as are
       warranted, including but not limited to public censure, suspension,
       or removal from the bench;
    d. Refer any criminal conduct to the appropriate prosecuting authority.

VII. VERIFICATION

    I, Andrew J. Pigors, declare under penalty of perjury that the statements
in this complaint are true and correct to the best of my knowledge,
information, and belief.


________________________________________
ANDREW J. PIGORS, Complainant
Dated: {self.TODAY}

"""
        doc += self._build_verification()
        return doc

    def _gen_coa_leave_application(self, lane: str, conn, info: Dict) -> str:
        """MCR 7.205 — Court of Appeals Application for Leave to Appeal."""
        claims = self._get_claims(conn)
        authorities = self._get_authorities(conn)

        width = 72
        doc = f"""{'STATE OF MICHIGAN'.center(width)}
{'IN THE COURT OF APPEALS'.center(width)}

ANDREW J. PIGORS,
    Plaintiff-Appellant,                COA Case No. _______________

        v.                              Lower Court: {info['court']}
                                        Lower Court Case No. {info['case_number']}
{info['defendant']},                    {info['judge']}
    Defendant(s)-Appellee(s).
{'=' * width}
ANDREW J. PIGORS (Pro Se)
[Address]
[City, State ZIP]
[Phone]
[Email]
{'=' * width}

{'APPLICATION FOR LEAVE TO APPEAL'.center(width)}
{'(MCR 7.205)'.center(width)}

I. ORDER BEING APPEALED

    1. Plaintiff-Appellant, Andrew J. Pigors, hereby applies for leave to
appeal from the Order of {info['judge']}, entered on [DATE], in the
{info['court']}, Case No. {info['case_number']}.

    2. A copy of the order being appealed is attached as Appendix A.

II. STATEMENT OF JURISDICTION

    3. This Court has jurisdiction pursuant to MCL 600.308 and MCR 7.203.
This application is timely filed within 21 days of the order being
appealed, per MCR 7.205(A).

III. STATEMENT OF QUESTIONS PRESENTED

"""
        for i, c in enumerate(claims[:5], 1):
            doc += f"    {i}. Whether the trial court erred in its handling of: {c['claim_type'].replace('_', ' ').title()}?\n\n"
            doc += f"       Plaintiff-Appellant answers: Yes.\n\n"

        if not claims:
            doc += """    1. Whether the trial court erred in [specific ruling]?
       Plaintiff-Appellant answers: Yes.

    2. Whether the trial court abused its discretion in [specific action]?
       Plaintiff-Appellant answers: Yes.

"""

        doc += f"""
IV. STATEMENT OF FACTS

    4. [Detailed factual summary to be developed from case database]

V. ARGUMENT

    A. STANDARD OF REVIEW

    5. Questions of law are reviewed de novo. Eggleston v. Bio-Medical
Applications of Detroit, Inc., 468 Mich 29, 32 (2003). Factual findings
are reviewed for clear error. MCR 2.613(C). Discretionary rulings are
reviewed for abuse of discretion. Maldonado v. Ford Motor Co., 476 Mich
372, 388 (2006).

    B. THE TRIAL COURT ERRED

    6. [Specific arguments to be developed]

"""
        for a in authorities[:8]:
            doc += f"    See {a['citation_text']}\n"

        doc += f"""

VI. RELIEF REQUESTED

    WHEREFORE, Plaintiff-Appellant respectfully requests that this
Honorable Court:

    a. Grant this Application for Leave to Appeal;
    b. Reverse the trial court's Order of [DATE];
    c. Remand for further proceedings consistent with this Court's opinion;
    d. Grant such other relief as the Court deems just and proper.

Respectfully submitted,


________________________________________
ANDREW J. PIGORS, Pro Se Plaintiff-Appellant
Dated: {self.TODAY}
"""
        doc += self._build_certificate_of_service(info)
        return doc

    def _gen_complaint_1983(self, lane: str, conn, info: Dict) -> str:
        """42 U.S.C. § 1983 — Civil Rights Complaint."""
        claims = self._get_claims(conn)
        evidence = self._get_evidence(conn)
        witnesses = self._get_witnesses(conn)

        width = 72
        doc = f"""{'UNITED STATES DISTRICT COURT'.center(width)}
{'WESTERN DISTRICT OF MICHIGAN'.center(width)}
{'SOUTHERN DIVISION'.center(width)}

ANDREW J. PIGORS,
    Plaintiff,                          Case No. _______________

        v.                              JURY TRIAL DEMANDED

COUNTY OF MUSKEGON; [INDIVIDUAL
DEFENDANTS IN THEIR INDIVIDUAL
AND OFFICIAL CAPACITIES],
    Defendants.
{'=' * width}
ANDREW J. PIGORS (Pro Se)
[Address]
[City, State ZIP]
[Phone]
[Email]
{'=' * width}

{'COMPLAINT UNDER 42 U.S.C. § 1983'.center(width)}

    Plaintiff, Andrew J. Pigors, appearing pro se, brings this Complaint
against the above-named Defendants and in support thereof alleges as follows:

I. INTRODUCTION

    1. This is a civil rights action brought pursuant to 42 U.S.C. § 1983
for deprivation of rights secured by the Fourth, Fifth, and Fourteenth
Amendments to the United States Constitution.

    2. Plaintiff seeks compensatory and punitive damages, declaratory relief,
and injunctive relief for the violations described herein.

II. JURISDICTION AND VENUE

    3. This Court has subject matter jurisdiction pursuant to 28 U.S.C.
§ 1331 (federal question) and 28 U.S.C. § 1343 (civil rights).

    4. Venue is proper in this District pursuant to 28 U.S.C. § 1391(b)
because a substantial part of the events giving rise to the claims
occurred in Muskegon County, Michigan, which is within this District.

    5. This Court has supplemental jurisdiction over Plaintiff's state law
claims pursuant to 28 U.S.C. § 1367.

III. PARTIES

    6. Plaintiff Andrew J. Pigors is a citizen and resident of Muskegon
County, Michigan, and was at all relevant times a "person" within the
meaning of 42 U.S.C. § 1983.

    7. Defendant County of Muskegon is a municipal entity organized under
the laws of the State of Michigan. The County is a "person" subject to
suit under 42 U.S.C. § 1983 pursuant to Monell v. Department of Social
Services, 436 U.S. 658 (1978).

"""
        # Add individual defendants from witnesses
        defendant_num = 8
        for w in witnesses[:5]:
            if w.get('role') in ('defendant', 'judge', 'government'):
                doc += f"    {defendant_num}. Defendant {w['name']} is [title/position] and was\n"
                doc += f"at all relevant times acting under color of state law.\n\n"
                defendant_num += 1

        doc += f"""
IV. STATEMENT OF FACTS

"""
        fact_num = defendant_num
        for e in evidence[:12]:
            doc += f"    {fact_num}. {e['description'][:250]}\n\n"
            fact_num += 1

        if not evidence:
            doc += f"""    {fact_num}. [Detailed factual allegations to be inserted from case database]

"""
            fact_num += 1

        doc += f"""
V. CAUSES OF ACTION

COUNT I — 42 U.S.C. § 1983: DEPRIVATION OF DUE PROCESS
(Fourteenth Amendment)

    {fact_num}. Plaintiff incorporates all preceding paragraphs by reference.

    {fact_num + 1}. Defendants, acting under color of state law, deprived Plaintiff
of his rights to procedural and substantive due process guaranteed by the
Fourteenth Amendment to the United States Constitution.

    {fact_num + 2}. Defendants' conduct was undertaken with deliberate indifference
to Plaintiff's constitutional rights and was the proximate cause of
Plaintiff's injuries.

COUNT II — 42 U.S.C. § 1983: EQUAL PROTECTION
(Fourteenth Amendment)

    {fact_num + 3}. Plaintiff incorporates all preceding paragraphs by reference.

    {fact_num + 4}. Defendants treated Plaintiff differently from similarly situated
individuals without rational basis, in violation of the Equal Protection
Clause of the Fourteenth Amendment.

"""
        # Add Monell claim
        doc += f"""COUNT III — 42 U.S.C. § 1983: MONELL LIABILITY
(Municipal Policy or Custom)

    {fact_num + 5}. Plaintiff incorporates all preceding paragraphs by reference.

    {fact_num + 6}. The constitutional violations described herein were caused by an
official policy, widespread custom, or deliberate indifference of the
County of Muskegon, as required by Monell v. Department of Social Services,
436 U.S. 658 (1978).

    {fact_num + 7}. The County's failure to train, supervise, and discipline its
employees and officials constitutes deliberate indifference to Plaintiff's
constitutional rights. City of Canton v. Harris, 489 U.S. 378 (1989).

"""

        # Add additional counts from claims
        count_num = 4
        for c in claims[:4]:
            ct = c['claim_type'].replace('_', ' ').upper()
            doc += f"""COUNT {_roman(count_num)} — {ct}

    Plaintiff incorporates all preceding paragraphs by reference.

    {c['description'][:300]}

"""
            count_num += 1

        doc += f"""
VI. DAMAGES

    Plaintiff has suffered and continues to suffer the following damages
as a direct and proximate result of Defendants' conduct:

    a. Loss of constitutionally protected parental rights;
    b. Emotional distress, anxiety, and mental anguish;
    c. Loss of companionship with minor child(ren);
    d. Economic damages including [costs, lost wages, expenses];
    e. Damage to reputation;
    f. Attorney fees and costs (or pro se litigation expenses).

VII. PRAYER FOR RELIEF

    WHEREFORE, Plaintiff respectfully requests that this Court:

    a. Enter judgment in Plaintiff's favor on all Counts;
    b. Award compensatory damages in an amount to be proven at trial;
    c. Award punitive damages against individual Defendants;
    d. Issue a declaratory judgment that Defendants' conduct violated
       Plaintiff's constitutional rights;
    e. Issue injunctive relief preventing continued violations;
    f. Award reasonable attorney fees (or pro se litigation costs)
       pursuant to 42 U.S.C. § 1988;
    g. Award pre-judgment and post-judgment interest;
    h. Grant such other and further relief as the Court deems just.

JURY DEMAND

    Plaintiff hereby demands a trial by jury on all issues so triable.

Respectfully submitted,


________________________________________
ANDREW J. PIGORS, Pro Se Plaintiff
Dated: {self.TODAY}
"""
        doc += self._build_verification()
        doc += self._build_certificate_of_service(info)
        return doc

    def _gen_proposed_order(self, lane: str, conn, info: Dict) -> str:
        """MCR 2.602 — Proposed Order."""
        doc = self._build_caption(info, "PROPOSED ORDER", "MCR 2.602")
        doc += f"""
    At a session of said Court held in the
    {info['county']} County Courthouse,
    City of Muskegon, State of Michigan,
    on the _____ day of _______________, {date.today().year}.

PRESENT: {info['judge']}

    This matter having come before the Court on Plaintiff's Motion
[specify motion type], and the Court having reviewed the Motion, Brief
in Support, Affidavit(s), exhibits, and all other filings in this matter,
and the Court being otherwise fully advised in the premises;

    IT IS HEREBY ORDERED that:

    1. Plaintiff's Motion is GRANTED.

    2. [Specific relief ordered — to be tailored per motion type]

    3. [Additional provisions as needed]

    4. This Order is effective immediately upon entry.


                                    ________________________________________
                                    {info['judge']}
                                    {info['court']}

Date: ____________________


    I declare that this proposed order has been approved as to form by:

    _______ Approved as to form
    _______ Objected to for the following reasons: _______________

    ________________________________________
    [Opposing party / attorney]
    Date: ____________________
"""
        return doc

    def _gen_certificate_of_service(self, lane: str, conn, info: Dict) -> str:
        """MCR 2.107 — Standalone Certificate of Service."""
        doc = self._build_caption(info, "CERTIFICATE OF SERVICE", "MCR 2.107")
        doc += f"""
    I, Andrew J. Pigors, hereby certify under MCR 2.107 that on
{self.TODAY}, I served true and correct copies of the following documents:

    1. [Document 1 Title]
    2. [Document 2 Title]
    3. [Document 3 Title]

upon all parties entitled to service, by the following method(s):

METHOD OF SERVICE:

    [X] First-class United States Mail, postage fully prepaid, addressed to:

        {info['defendant']}
        c/o [Attorney Name]
        [Address Line 1]
        [City, State ZIP]

    [ ] Personal service / hand delivery

    [ ] Electronic service via Michigan's MiFILE e-filing system

    [ ] Email transmission (with prior written consent of recipient)
        Email: [email address]

    [ ] Facsimile transmission
        Fax: [fax number]

ADDITIONAL PARTIES SERVED:

    [Name]
    [Address]
    [City, State ZIP]
    Method: [ ] Mail  [ ] Personal  [ ] Electronic  [ ] Email


    I declare under the penalties of perjury that the foregoing is true
and correct.


                                    ________________________________________
                                    ANDREW J. PIGORS, Pro Se Plaintiff
                                    Dated: {self.TODAY}
"""
        return doc

    # ── Dispatch ─────────────────────────────────────────────────────────

    GENERATOR_MAP = {
        "motion_summary_disposition": "_gen_motion_summary_disposition",
        "motion_disqualify": "_gen_motion_disqualify",
        "motion_parenting_time": "_gen_motion_parenting_time",
        "brief_in_support": "_gen_brief_in_support",
        "affidavit": "_gen_affidavit",
        "jtc_complaint": "_gen_jtc_complaint",
        "coa_leave_application": "_gen_coa_leave_application",
        "complaint_1983": "_gen_complaint_1983",
        "proposed_order": "_gen_proposed_order",
        "certificate_of_service": "_gen_certificate_of_service",
    }

    def generate_document(self, doc_type: str, lane: str) -> Optional[Path]:
        """Generate a single court document for the specified lane."""
        if doc_type not in self.DOCUMENT_TYPES:
            log.error(f"Unknown document type: {doc_type}")
            log.info(f"Available types: {list(self.DOCUMENT_TYPES.keys())}")
            return None

        if lane not in LANES:
            log.error(f"Unknown lane: {lane}")
            return None

        cfg = LANES[lane]
        doc_cfg = self.DOCUMENT_TYPES[doc_type]

        conn = self._open_case_db(lane)
        info = self._get_case_info(conn, lane)

        method_name = self.GENERATOR_MAP.get(doc_type)
        if not method_name:
            log.error(f"No generator for: {doc_type}")
            return None

        generator = getattr(self, method_name)
        content = generator(lane, conn, info)

        if conn:
            conn.close()

        # Write to file
        out_dir = COURT_DOC_DIR / cfg["doc_subdir"] / doc_cfg["subdir"]
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / doc_cfg["filename"]

        # Add generation header
        header = f"""{'=' * 72}
GENERATED DOCUMENT — DRAFT FOR REVIEW
Generated: {datetime.now().isoformat()}
Lane: {lane} — {cfg['case_name']}
Case: {cfg['case_number']}
Type: {doc_cfg['title']}
Rule: {doc_cfg['mcr']}

WARNING: This is a computer-generated draft. All content must be reviewed,
verified, and completed before filing with any court. Bracketed items
[like this] require manual completion.
{'=' * 72}

"""
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(header + content)

        log.info(f"  Generated: {out_path}")

        # Track filing in case DB if available
        self._track_filing(lane, doc_type, doc_cfg, out_path)

        return out_path

    def _track_filing(self, lane: str, doc_type: str, doc_cfg: Dict, out_path: Path):
        """Record the generated document in the case database filings table."""
        try:
            cfg = LANES[lane]
            db_path = CASE_DB_DIR / cfg["db_file"]
            if not db_path.exists():
                return
            conn = sqlite3.connect(str(db_path))
            conn.execute(
                "INSERT INTO filings (filing_type, title, file_path, status, notes) "
                "VALUES (?, ?, ?, 'draft', ?)",
                (
                    doc_type,
                    doc_cfg["title"],
                    str(out_path),
                    f"Auto-generated {datetime.now().isoformat()}",
                ),
            )
            conn.commit()
            conn.close()
        except Exception as e:
            log.debug(f"Could not track filing: {e}")

    def generate_all_for_lane(self, lane: str):
        """Generate all document types for a single lane."""
        log.info(f"═══ Generating all documents for Lane {lane} ═══")
        for doc_type in self.DOCUMENT_TYPES:
            try:
                self.generate_document(doc_type, lane)
            except Exception as e:
                log.error(f"  Failed to generate {doc_type}: {e}")
        log.info(f"═══ Lane {lane} document generation complete ═══\n")

    def generate_all(self):
        """Generate all document types for all lanes."""
        log.info("Generating all court documents for all lanes...")
        for lane in LANES:
            self.generate_all_for_lane(lane)
        log.info("All court document generation complete.")


# ════════════════════════════════════════════════════════════════════════════════
#  CASE STATUS REPORTER
# ════════════════════════════════════════════════════════════════════════════════

class CaseReporter:
    """Generates status reports from per-case databases."""

    def report(self, lanes: Optional[List[str]] = None):
        """Print a comprehensive status report."""
        target_lanes = lanes or list(LANES.keys())
        width = 72

        print(f"\n{'=' * width}")
        print("LITIGATION STATUS REPORT".center(width))
        print(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}".center(width))
        print(f"{'=' * width}\n")

        for lane in target_lanes:
            self._report_lane(lane, width)

    def _report_lane(self, lane: str, width: int):
        """Report on a single lane."""
        cfg = LANES[lane]
        db_path = CASE_DB_DIR / cfg["db_file"]

        print(f"{'─' * width}")
        print(f" LANE {lane}: {cfg['case_name']}")
        print(f" Case No. {cfg['case_number']} | {cfg['judge']} | {cfg['court']}")
        print(f"{'─' * width}")

        if not db_path.exists():
            print("  ⚠  Database not built. Run: python case_database_builder.py build\n")
            return

        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row

        tables = [
            ("evidence", "Evidence Items"),
            ("claims", "Active Claims"),
            ("timeline", "Timeline Events"),
            ("witnesses", "Witnesses"),
            ("authorities", "Legal Authorities"),
            ("opposition_analysis", "Opposition Notes"),
            ("damages", "Damage Categories"),
            ("filings", "Filings"),
            ("action_items", "Action Items"),
        ]

        for table, label in tables:
            try:
                count = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
                status = "✓" if count > 0 else "○"
                print(f"  {status} {label}: {count}")
            except Exception:
                print(f"  ✗ {label}: error")

        # Top claims by strength
        try:
            claims = conn.execute(
                "SELECT claim_type, strength_score FROM claims "
                "WHERE status = 'active' ORDER BY strength_score DESC LIMIT 5"
            ).fetchall()
            if claims:
                print(f"\n  Top Claims:")
                for c in claims:
                    bar = "█" * (c["strength_score"] // 10) if c["strength_score"] else ""
                    print(f"    {c['claim_type']:<30} [{bar:<10}] {c['strength_score'] or 0}/100")
        except Exception:
            pass

        # Urgent action items
        try:
            items = conn.execute(
                "SELECT description, priority FROM action_items "
                "WHERE status IN ('pending','in_progress') ORDER BY priority LIMIT 5"
            ).fetchall()
            if items:
                print(f"\n  Pending Actions:")
                for item in items:
                    pri = {1: "🔴", 2: "🟡", 3: "⚪", 4: "⚫"}.get(item["priority"], "⚪")
                    print(f"    {pri} {item['description'][:60]}")
        except Exception:
            pass

        # Filed documents
        try:
            filings = conn.execute(
                "SELECT title, status FROM filings ORDER BY created_at DESC LIMIT 5"
            ).fetchall()
            if filings:
                print(f"\n  Recent Filings:")
                for f in filings:
                    emoji = {"draft": "📝", "ready": "✅", "filed": "📬", "served": "📨"}.get(
                        f["status"], "📄"
                    )
                    print(f"    {emoji} [{f['status']}] {f['title'][:50]}")
        except Exception:
            pass

        conn.close()
        print()


# ════════════════════════════════════════════════════════════════════════════════
#  UTILITY FUNCTIONS
# ════════════════════════════════════════════════════════════════════════════════

def _roman(n: int) -> str:
    """Convert integer to Roman numeral."""
    vals = [
        (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
        (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
        (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
    ]
    result = ""
    for value, numeral in vals:
        while n >= value:
            result += numeral
            n -= value
    return result


# ════════════════════════════════════════════════════════════════════════════════
#  CLI ENTRY POINT
# ════════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="LitigationOS — Case Database Builder & Court Document Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python case_database_builder.py build                            Build all 3 case databases
              python case_database_builder.py build --lane A                   Build Lane A only
              python case_database_builder.py generate                         Generate all court documents
              python case_database_builder.py generate --type motion_disqualify --lane A
              python case_database_builder.py report                           Case status report
              python case_database_builder.py all                              Everything
        """),
    )

    parser.add_argument(
        "command",
        choices=["build", "generate", "report", "all"],
        help="Command to execute",
    )
    parser.add_argument(
        "--lane",
        choices=["A", "B", "C"],
        help="Target a specific case lane (default: all)",
    )
    parser.add_argument(
        "--type",
        dest="doc_type",
        choices=list(CourtDocumentGenerator.DOCUMENT_TYPES.keys()),
        help="Document type to generate (for 'generate' command)",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    log.info(f"LitigationOS Case Database Builder v1.0")
    log.info(f"Command: {args.command}" + (f" | Lane: {args.lane}" if args.lane else ""))

    # ── Execute commands ─────────────────────────────────────────────
    builder = CaseDatabaseBuilder()
    generator = CourtDocumentGenerator()
    reporter = CaseReporter()

    if args.command in ("build", "all"):
        if args.lane:
            builder.build_lane(args.lane)
        else:
            builder.build_all()

    if args.command in ("generate", "all"):
        if args.doc_type and args.lane:
            generator.generate_document(args.doc_type, args.lane)
        elif args.doc_type:
            for lane in LANES:
                generator.generate_document(args.doc_type, lane)
        elif args.lane:
            generator.generate_all_for_lane(args.lane)
        else:
            generator.generate_all()

    if args.command in ("report", "all"):
        reporter.report([args.lane] if args.lane else None)

    log.info("Done.")


if __name__ == "__main__":
    main()
