#!/usr/bin/env python
"""THEMANBEARPIG V5.0 — PyInstaller Build Script.

Generates a .spec file and prints build instructions for creating a
standalone THEMANBEARPIG.exe desktop application.

Usage:
    python -I scripts/mbp_build.py                    # One-dir build (default)
    python -I scripts/mbp_build.py --onefile           # Single .exe
    python -I scripts/mbp_build.py --windowed          # No console window
    python -I scripts/mbp_build.py --name MBP_V5       # Custom output name
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
APP_SCRIPT = REPO_ROOT / "scripts" / "mbp_app.py"
VIS_DIR = REPO_ROOT / "08_MEDIA" / "MANBEARPIG_V5"
BRAIN_DB = REPO_ROOT / "mbp_brain.db"
ICON_PATH = VIS_DIR / "icon.ico"
SPEC_OUTPUT = REPO_ROOT / "THEMANBEARPIG.spec"
DEFAULT_NAME = "THEMANBEARPIG"


def _check_pyinstaller() -> bool:
    """Return True if PyInstaller is importable."""
    try:
        import PyInstaller  # noqa: F401
        return True
    except ImportError:
        return False


def _collect_data_files() -> list[tuple[str, str]]:
    """Build the datas list for PyInstaller: (source, dest_dir) tuples."""
    datas: list[tuple[str, str]] = []

    # HTML visualisation files
    if VIS_DIR.exists():
        for f in VIS_DIR.iterdir():
            if f.is_file():
                datas.append((str(f), "MANBEARPIG_V5"))
    else:
        print(f"WARNING: Vis directory not found: {VIS_DIR}", file=sys.stderr)

    # Brain database — shipped alongside the exe, NOT embedded in onefile
    if BRAIN_DB.exists():
        datas.append((str(BRAIN_DB), "."))
    else:
        print(f"WARNING: Brain DB not found: {BRAIN_DB}", file=sys.stderr)

    return datas


def generate_spec(
    name: str = DEFAULT_NAME,
    onefile: bool = False,
    windowed: bool = False,
) -> str:
    """Generate a PyInstaller .spec file as a string."""
    datas = _collect_data_files()

    # Format datas list for the spec
    datas_str = "[\n"
    for src, dst in datas:
        # Use raw string repr to handle Windows backslashes
        datas_str += f"        ({src!r}, {dst!r}),\n"
    datas_str += "    ]"

    # Hidden imports needed by pywebview on Windows
    hidden_imports = [
        "webview",
        "webview.platforms.edgechromium",
        "webview.platforms.winforms",
        "clr",
        "clr_loader",
        "pythonnet",
        "System",
        "System.Windows.Forms",
        "System.Drawing",
        "System.Threading",
        "http.server",
        "socketserver",
    ]
    hidden_str = repr(hidden_imports)

    icon_line = ""
    if ICON_PATH.exists():
        icon_line = f"    icon={str(ICON_PATH)!r},"
    else:
        icon_line = "    icon=None,  # No icon.ico found — add one to 08_MEDIA/MANBEARPIG_V5/"

    if onefile:
        spec = f'''# -*- mode: python ; coding: utf-8 -*-
# THEMANBEARPIG V5.0 — PyInstaller Spec (one-file mode)
# Generated by scripts/mbp_build.py
#
# Build with:  pyinstaller THEMANBEARPIG.spec
#
# NOTE: The 257+ MB mbp_brain.db is bundled as a data file.
#       In one-file mode it is extracted to a temp directory at runtime.
#       For faster startup, prefer one-dir mode (--onedir).

block_cipher = None

a = Analysis(
    [{str(APP_SCRIPT)!r}],
    pathex=[{str(REPO_ROOT)!r}],
    binaries=[],
    datas={datas_str},
    hiddenimports={hidden_str},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "pandas", "scipy"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name={name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console={not windowed},
{icon_line}
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''
    else:
        spec = f'''# -*- mode: python ; coding: utf-8 -*-
# THEMANBEARPIG V5.0 — PyInstaller Spec (one-dir mode)
# Generated by scripts/mbp_build.py
#
# Build with:  pyinstaller THEMANBEARPIG.spec
#
# One-dir mode is RECOMMENDED for this project because:
#   - mbp_brain.db is 257+ MB — one-file would extract it to temp on every launch
#   - Faster startup: no temp extraction needed
#   - Easier to update graph_data.json without rebuilding

block_cipher = None

a = Analysis(
    [{str(APP_SCRIPT)!r}],
    pathex=[{str(REPO_ROOT)!r}],
    binaries=[],
    datas={datas_str},
    hiddenimports={hidden_str},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "pandas", "scipy"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name={name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console={not windowed},
{icon_line}
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name={name!r},
)
'''

    return spec


def main() -> None:
    parser = argparse.ArgumentParser(
        description="THEMANBEARPIG V5.0 — Generate PyInstaller build spec"
    )
    parser.add_argument(
        "--onefile", action="store_true",
        help="Single-file EXE (slower startup due to 257MB DB extraction)"
    )
    parser.add_argument(
        "--windowed", action="store_true",
        help="No console window (--noconsole / -w)"
    )
    parser.add_argument(
        "--name", type=str, default=DEFAULT_NAME,
        help=f"Output executable name (default: {DEFAULT_NAME})"
    )
    args = parser.parse_args()

    has_pyinstaller = _check_pyinstaller()

    # -- Validate prerequisites ----------------------------------------
    missing = []
    if not APP_SCRIPT.exists():
        missing.append(f"  - App script: {APP_SCRIPT}")
    if not VIS_DIR.exists():
        missing.append(f"  - Vis directory: {VIS_DIR}")
    if not BRAIN_DB.exists():
        missing.append(f"  - Brain DB: {BRAIN_DB}")

    if missing:
        print("WARNING: Missing files (build may fail):", file=sys.stderr)
        for m in missing:
            print(m, file=sys.stderr)
        print()

    # -- Generate spec file --------------------------------------------
    spec_content = generate_spec(
        name=args.name,
        onefile=args.onefile,
        windowed=args.windowed,
    )

    SPEC_OUTPUT.write_text(spec_content, encoding="utf-8")
    print(f"Spec file written to: {SPEC_OUTPUT}")
    print()

    # -- Print build summary -------------------------------------------
    mode = "one-file" if args.onefile else "one-dir (recommended)"
    console = "windowed (no console)" if args.windowed else "console"
    icon_status = "YES" if ICON_PATH.exists() else "NO (add icon.ico to 08_MEDIA/MANBEARPIG_V5/)"

    datas = _collect_data_files()
    total_mb = 0.0
    for src, _ in datas:
        p = Path(src)
        if p.exists():
            total_mb += p.stat().st_size / (1024 * 1024)

    print("=" * 62)
    print("  THEMANBEARPIG V5.0 — Build Configuration")
    print("=" * 62)
    print(f"  Output name .... {args.name}.exe")
    print(f"  Mode ........... {mode}")
    print(f"  Console ........ {console}")
    print(f"  Icon ........... {icon_status}")
    print(f"  Data files ..... {len(datas)} files ({total_mb:.1f} MB)")
    print(f"  Spec file ...... {SPEC_OUTPUT}")
    print("-" * 62)

    if not has_pyinstaller:
        print()
        print("  PyInstaller is NOT installed.")
        print("  Install with:  pip install pyinstaller")
        print()

    print()
    print("  To build, run:")
    print()
    print(f"    cd {REPO_ROOT}")
    if not has_pyinstaller:
        print("    pip install pyinstaller")
    print(f"    pyinstaller {SPEC_OUTPUT.name}")
    print()
    print(f"  Output will be in: {REPO_ROOT / 'dist' / args.name}")
    if args.onefile:
        print()
        print("  ⚠ One-file mode bundles the 257+ MB brain database.")
        print("    Every launch extracts it to a temp folder — expect slow startup.")
        print("    Consider one-dir mode (default) for faster startup.")
    else:
        print()
        print("  The dist/ folder will contain:")
        print(f"    dist/{args.name}/{args.name}.exe")
        print(f"    dist/{args.name}/MANBEARPIG_V5/index.html")
        print(f"    dist/{args.name}/MANBEARPIG_V5/graph_data.json")
        print(f"    dist/{args.name}/mbp_brain.db")
    print()
    print("=" * 62)


if __name__ == "__main__":
    main()
