#!/usr/bin/env python3
"""THEMANBEARPIG Build Script — PyInstaller bundler for the unified legal brain.

Usage:
    python scripts/themanbearpig_build.py              # One-dir build (recommended)
    python scripts/themanbearpig_build.py --onefile     # Single .exe (slower startup)
    python scripts/themanbearpig_build.py --windowed    # No console window
    python scripts/themanbearpig_build.py --name NAME   # Custom exe name
    python scripts/themanbearpig_build.py --help        # Show help
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENTRY_POINT = REPO_ROOT / "scripts" / "themanbearpig.py"
VIS_DIR_V9 = REPO_ROOT / "08_MEDIA" / "MANBEARPIG_V9"
VIS_DIR_V5 = REPO_ROOT / "08_MEDIA" / "MANBEARPIG_V5"
GRAPH_JSON_V9 = VIS_DIR_V9 / "graph_data.json"
GRAPH_JSON_V5 = VIS_DIR_V5 / "graph_data.json"
BRAIN_DB = REPO_ROOT / "mbp_brain.db"
ICON_PATH = REPO_ROOT / "08_MEDIA" / "chatgpt_image_apr_30__2025__12_12_28_am_5j0_icon_1.ico"
ICON_FALLBACK = REPO_ROOT / "08_MEDIA" / "manbearpig_encyclopedia.ico"
DIST_DIR = REPO_ROOT / "dist"
BUILD_DIR = REPO_ROOT / "build"

HIDDEN_IMPORTS = [
    "webview",
    "sqlite3",
    "threading",
    "http.server",
    "json",
    "re",
    "subprocess",
    "hashlib",
    "socket",
    "mimetypes",
    "argparse",
]

EXCLUDES = [
    "tkinter",
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "torch",
    "transformers",
    "sentence_transformers",
    "lancedb",
    "duckdb",
    "polars",
    "IPython",
    "jupyter",
    "notebook",
    "PIL",
    "cv2",
    "sklearn",
    "test",
    "unittest",
    "doctest",
    "pydoc",
    "xmlrpc",
]


def collect_data_files():
    """Collect all data files to bundle."""
    datas = []

    if VIS_DIR_V9.exists():
        for f in VIS_DIR_V9.iterdir():
            if f.is_file():
                datas.append((str(f), "08_MEDIA/MANBEARPIG_V9"))

    # V9 graph_data.json is the primary, V5 as fallback
    if GRAPH_JSON_V9.exists():
        pass  # already included from V9 dir iteration
    elif GRAPH_JSON_V5.exists():
        datas.append((str(GRAPH_JSON_V5), "08_MEDIA/MANBEARPIG_V9"))

    return datas


def generate_spec(name, onefile, windowed):
    """Generate a PyInstaller .spec file programmatically."""
    datas = collect_data_files()
    datas_str = ",\n        ".join(f"({repr(str(s))}, {repr(d)})" for s, d in datas)

    hiddens_str = ", ".join(f"'{h}'" for h in HIDDEN_IMPORTS)
    excludes_str = ", ".join(f"'{e}'" for e in EXCLUDES)

    icon_actual = ICON_PATH if ICON_PATH.exists() else (ICON_FALLBACK if ICON_FALLBACK.exists() else None)
    icon_line = f"icon={repr(str(icon_actual))}," if icon_actual else ""
    console_val = "False" if windowed else "True"

    if onefile:
        spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by themanbearpig_build.py

a = Analysis(
    [{repr(str(ENTRY_POINT))}],
    pathex=[{repr(str(REPO_ROOT))}],
    binaries=[],
    datas=[
        {datas_str}
    ],
    hiddenimports=[{hiddens_str}],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[{excludes_str}],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={repr(name)},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console={console_val},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    {icon_line}
)
"""
    else:
        spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by themanbearpig_build.py

a = Analysis(
    [{repr(str(ENTRY_POINT))}],
    pathex=[{repr(str(REPO_ROOT))}],
    binaries=[],
    datas=[
        {datas_str}
    ],
    hiddenimports=[{hiddens_str}],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[{excludes_str}],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name={repr(name)},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console={console_val},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    {icon_line}
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name={repr(name)},
)
"""
    return spec


def preflight_checks():
    """Verify prerequisites before building."""
    errors = []

    if not ENTRY_POINT.exists():
        errors.append(f"Entry point not found: {ENTRY_POINT}")

    v9_index = VIS_DIR_V9 / "index.html"
    if not v9_index.exists():
        errors.append(f"V9 index.html not found: {v9_index}")

    try:
        import PyInstaller
    except ImportError:
        errors.append("PyInstaller not installed. Run: pip install pyinstaller")

    try:
        import webview
    except ImportError:
        errors.append("pywebview not installed. Run: pip install pywebview")

    if not GRAPH_JSON_V9.exists() and not GRAPH_JSON_V5.exists():
        print(f"WARNING: graph_data.json not found in V9 or V5 dirs")
        print("  The brain graph tab will not work without it.")
        print("  Run: python -I scripts/export_brain_d3.py")

    if not BRAIN_DB.exists():
        print(f"WARNING: mbp_brain.db not found at {BRAIN_DB}")
        print("  Brain features will be unavailable.")

    return errors


def build(name, onefile, windowed, clean):
    """Execute the PyInstaller build."""
    errors = preflight_checks()
    if errors:
        print("BUILD FAILED — preflight errors:")
        for e in errors:
            print(f"  ✗ {e}")
        return 1

    spec_content = generate_spec(name, onefile, windowed)
    spec_path = REPO_ROOT / f"{name}.spec"
    with open(str(spec_path), "w", encoding="utf-8") as f:
        f.write(spec_content)
    print(f"Generated spec: {spec_path}")

    if clean:
        for d in (BUILD_DIR, DIST_DIR):
            if d.exists():
                print(f"Cleaning {d}...")
                shutil.rmtree(str(d), ignore_errors=True)

    cmd = [
        sys.executable, "-m", "PyInstaller",
        str(spec_path),
        "--distpath", str(DIST_DIR),
        "--workpath", str(BUILD_DIR),
        "--noconfirm",
    ]

    print(f"\nBuilding {name}...")
    print(f"  Mode: {'onefile' if onefile else 'one-dir'}")
    print(f"  Console: {'hidden' if windowed else 'visible'}")
    print(f"  Command: {' '.join(cmd)}\n")

    result = subprocess.run(cmd, cwd=str(REPO_ROOT))

    if result.returncode == 0:
        if onefile:
            exe_path = DIST_DIR / f"{name}.exe"
        else:
            exe_path = DIST_DIR / name / f"{name}.exe"
        print(f"\n{'=' * 60}")
        print(f"BUILD SUCCESSFUL")
        print(f"  Executable: {exe_path}")
        if exe_path.exists():
            size_mb = exe_path.stat().st_size / 1048576
            print(f"  Size: {size_mb:.1f} MB")
        print(f"\nTo run:")
        print(f"  {exe_path}")
        if not onefile:
            print(f"\nNOTE: Copy mbp_brain.db into {DIST_DIR / name}/ for brain features.")
        print(f"{'=' * 60}")
    else:
        print(f"\nBUILD FAILED (exit code {result.returncode})")
        print("Check the output above for errors.")

    if spec_path.exists():
        try:
            os.remove(str(spec_path))
        except Exception:
            pass

    return result.returncode


def main():
    parser = argparse.ArgumentParser(
        description="THEMANBEARPIG Build — PyInstaller bundler for the unified legal brain"
    )
    parser.add_argument("--onefile", action="store_true",
                        help="Build as single .exe (slower startup, easier distribution)")
    parser.add_argument("--windowed", action="store_true",
                        help="Hide console window (use for production)")
    parser.add_argument("--name", default="THEMANBEARPIG",
                        help="Executable name (default: THEMANBEARPIG)")
    parser.add_argument("--clean", action="store_true",
                        help="Clean build/dist directories before building")
    parser.add_argument("--spec-only", action="store_true",
                        help="Generate .spec file only, do not build")
    args = parser.parse_args()

    print(f"THEMANBEARPIG Build System")
    print(f"  Repo root: {REPO_ROOT}")
    print(f"  Entry point: {ENTRY_POINT}")
    print()

    if args.spec_only:
        spec = generate_spec(args.name, args.onefile, args.windowed)
        spec_path = REPO_ROOT / f"{args.name}.spec"
        with open(str(spec_path), "w", encoding="utf-8") as f:
            f.write(spec)
        print(f"Spec file written to: {spec_path}")
        return 0

    return build(args.name, args.onefile, args.windowed, args.clean)


if __name__ == "__main__":
    sys.exit(main())
