@echo off
setlocal enabledelayedexpansion

:: ROOT directory
set ROOT=F:\

:: Target Folders
set TARGETS=Exhibits Motions Orders CourtBundles SHADYOAKS-EVIDENCE FRED-PRIME-EVIDENCE "FRED PRIME" FEDERAL Certificates AutoGenerated Matrix Matrices Logs Dashboards Compliance Data FRED_PRIME_MATRIX FRED_PRIME_FULL_BUNDLE_ZIP FRED_PRIME_ANALYSIS_OUTPUT

:: Log file
set LOG=%ROOT%organizer_move_log.txt
echo ORGANIZATION STARTED > "%LOG%"

cd /d %ROOT%

for %%F in (*.*) do (
    set FILE=%%~nxF
    set LOWERFILE=!FILE!.LCase

    set MOVED=0

    if "!FILE!"=="organize_f_drive.bat" goto :continue
    if /I "!FILE!"=="organize_f_drive.py" goto :continue

    :: Match by keywords
    for %%T in (%TARGETS%) do (
        echo !FILE! | findstr /i "%%T" >nul
        if not errorlevel 1 (
            move "!FILE!" "%ROOT%%%T\" >> "%LOG%"
            echo Moved !FILE! to %%T >> "%LOG%"
            set MOVED=1
            goto :continue
        )
    )

    :: Match by known patterns
    echo !FILE! | findstr /i "motion exhibit order shady fred evidence core matrix bundle zip certificate log" >nul
    if not errorlevel 1 (
        if not exist "%ROOT%Unsorted\" mkdir "%ROOT%Unsorted"
        move "!FILE!" "%ROOT%Unsorted\" >> "%LOG%"
        echo Moved !FILE! to Unsorted >> "%LOG%"
        set MOVED=1
    )

    :continue
)

echo ORGANIZATION COMPLETE >> "%LOG%"
echo Done. See organizer_move_log.txt for details.
pause
