"""
PACKAGE UPGRADE ENGINE
Injects new authority into targeted packages and builds cross-package strategy layer.
"""
import json, os
from datetime import datetime

D99 = r"I:\LitigationOS_Delta99"
LOG = r"I:\DRIVE_ORG\operations.log"

def log(msg):
    ts = datetime.now().isoformat()
    line = f"[{ts}] {msg}"
    print(line)
    with open(LOG, "a", encoding="utf-8") as f:
        f.write(line + "\n")

def write_md(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

# ============================================================
# 1. PKG10 — DOCTRINE DEFENSE MATRIX
# ============================================================
def upgrade_pkg10():
    pkg = os.path.join(D99, "PKG10_FEDERAL_1983")
    
    # Load doctrine matrix
    with open(os.path.join(D99, "DOCTRINE_DEFENSE_MATRIX.json"), "r") as f:
        doctrines = json.load(f)
    
    content = """# DOCTRINE DEFENSE MATRIX — FEDERAL §1983/§1985 ACTION

## Pigors v. Watson et al. | U.S. District Court, Western District of Michigan

---

> **PURPOSE:** This document preemptively addresses every doctrinal defense
> that opposing counsel or the court will raise to dismiss the federal action.
> Each doctrine is analyzed with the specific counter-argument and controlling authority.

---

"""
    for key, d in doctrines.items():
        content += f"## {d['doctrine']}\n\n"
        content += f"### Opposing Argument\n{d['opposing_argument']}\n\n"
        content += f"### Your Counter-Argument\n{d['your_counter']}\n\n"
        content += f"### Controlling Authority\n"
        for case in d['key_cases']:
            content += f"- {case}\n"
        content += f"\n### 6th Circuit Authority\n{d['sixth_circuit']}\n\n---\n\n"
    
    content += """## STRATEGIC NOTES

1. **Frame claims as INDEPENDENT constitutional violations** — never as appeals from state orders
2. **Seek declaratory + injunctive relief** — not just damages (bypasses immunity barriers)
3. **Invoke Sprint v. Jacobs (2013)** immediately if Younger raised — it dramatically narrowed abstention
4. **Cite Ankenbrandt v. Richards (1992)** for domestic relations exception — it's narrow by SCOTUS's own holding
5. **Dennis v. Sparks (1980)** — private parties conspiring with judge are NOT immune
6. **42 USC 1988** — prevailing party gets attorney's fees (even pro se can recover costs)

---

*Generated by LitigationOS Authority Expansion Engine*
"""
    write_md(os.path.join(pkg, "DOCTRINE_DEFENSE_MATRIX.md"), content)
    
    # Also write immunity screening memo (was flagged as missing)
    immunity = """# IMMUNITY, ABSTENTION & JURISDICTION SCREENING MEMO

## PKG10 — Federal §1983/§1985 Action

---

## I. JURISDICTION ESTABLISHED

| Element | Basis | Authority |
|---------|-------|-----------|
| Subject Matter | Federal question | 28 USC 1331 |
| Civil Rights | Deprivation under color of state law | 28 USC 1343(a)(3) |
| Statutory Cause | Constitutional rights violated | 42 USC 1983 |
| Conspiracy | Joint action to deprive rights | 42 USC 1985(3) |

## II. IMMUNITY SCREENING

### A. Judicial Immunity — Judge McNeill
- **Status:** Partial immunity expected for judicial acts
- **Exception 1:** 42 USC 1983 permits injunctive relief where declaratory relief unavailable
- **Exception 2:** Acts in "clear absence of jurisdiction" not protected (*Stump v. Sparkman*)
- **Exception 3:** Conspiracy with private actor strips immunity (*Dennis v. Sparks*)
- **Strategy:** Seek DECLARATORY + INJUNCTIVE relief (not damages against judge)

### B. Qualified Immunity — FOC Staff / Other State Actors
- **Status:** Will be raised by individual defendants
- **Counter:** Right to parent-child relationship is "clearly established" since *Meyer* (1923)
- **Counter:** 571+ days separation without hearing — no reasonable official could believe constitutional
- **Counter:** *Guertin v. Michigan* (6th Cir. 2019) — denied QI where officials had notice of harm

### C. Prosecutorial Immunity — Opposing Counsel's Office
- **Status:** Mother employed by Kent County Prosecutor, Family Court Division
- **Analysis:** Prosecutors have absolute immunity for acts "intimately associated with the judicial phase"
- **Exception:** Administrative/investigative acts get only qualified immunity
- **Strategy:** If any prosecutorial resources were used in the custody case, this is an investigative act

## III. ABSTENTION SCREENING

### A. Rooker-Feldman
- **Risk Level:** MEDIUM — will be raised
- **Defense:** Claims are independent constitutional violations, not appeals
- **Key:** *Exxon Mobil v. Saudi Basic* (2005) narrowed doctrine
- **6th Circuit:** *McCormick v. Braverman* (2006)

### B. Younger Abstention
- **Risk Level:** LOW after *Sprint v. Jacobs* (2013)
- **Defense:** Custody proceedings don't fit any of 3 narrow Younger categories
- **Fallback:** Bad faith exception applies (ex parte orders without evidence)

### C. Domestic Relations Exception
- **Risk Level:** LOW
- **Defense:** *Ankenbrandt v. Richards* (1992) — exception is narrow
- **6th Circuit:** *Catz v. Chalker* (1998) — 1983 claims permitted in family court context

## IV. PASS/FAIL DETERMINATION

| Gate | Status | Notes |
|------|--------|-------|
| Jurisdiction | ✅ PASS | Federal question + civil rights |
| Standing | ✅ PASS | Direct injury — 571+ days separation |
| Rooker-Feldman | ✅ PASS | Independent claims, not state appeal |
| Younger | ✅ PASS | Sprint narrowing + bad faith exception |
| Domestic Relations | ✅ PASS | 1983 claim, not custody decree |
| Judicial Immunity | ⚠️ PARTIAL | Declaratory/injunctive relief available |
| Qualified Immunity | ✅ PASS | Clearly established rights violated |
| Statute of Limitations | ✅ PASS | 3 years in Michigan for 1983 claims |

**CONCLUSION:** Federal action is viable. Proceed with declaratory + injunctive relief framing.

---

*Generated by LitigationOS Authority Expansion Engine*
"""
    write_md(os.path.join(pkg, "IMMUNITY_ABSTENTION_SCREENING.md"), immunity)
    log(f"  PKG10: Doctrine defense matrix + immunity screening memo added")

# ============================================================
# 2. PKG06 — MCJC CANONS AUTHORITY
# ============================================================
def upgrade_pkg06():
    pkg = os.path.join(D99, "PKG06_JTC_COMPLAINT")
    
    content = """# MICHIGAN CODE OF JUDICIAL CONDUCT — FULL CANON REFERENCE

## Applicable to JTC Request for Investigation — Judge Jenny L. McNeill

---

## Canon 1: Integrity and Independence of the Judiciary
A judge should participate in establishing, maintaining, and enforcing high standards of conduct
so that the integrity and independence of the judiciary may be preserved.

**McNeill Violations:** Pattern of conduct undermining public confidence in judiciary.

## Canon 2: Avoid Impropriety and Appearance of Impropriety
(A) A judge should respect and comply with the law and act in a manner promoting public confidence.
(B) A judge should not allow family, social, or other relationships to influence judicial conduct.
(C) A judge should not hold membership in discriminatory organizations.

**McNeill Violations:** Appearance of bias; possible relationship influence (defendant's employment
at Kent County Prosecutor's Office, Family Court Division).

## Canon 3: Perform Duties Impartially and Diligently (AMENDED SEPT 1, 2025)
(A)(1) A judge should be faithful to the law and maintain professional competence.
(A)(3) A judge should be patient, dignified, and courteous to all.
(A)(4) A judge should accord every person the right to be heard according to law.
       A judge should not initiate, permit, or consider ex parte communications.
**(A)(5) A judge shall perform judicial duties without bias or prejudice.**

### ⚡ 2025 AMENDMENT (Effective September 1, 2025):
Canon 3 was amended to strengthen anti-bias provisions. Judges must not **"intentionally or
recklessly"** manifest bias, prejudice, or harassment based on protected characteristics including
race, sex, gender, religion, national origin, ethnicity, disability, age, sexual orientation,
marital status, or socioeconomic status. This brings Michigan closer to ABA Model Rule 2.3.

**SIGNIFICANCE FOR THIS CASE:** The 2025 amendment was in effect when many of the complained-of
actions occurred. The strengthened language ("intentionally or recklessly") lowers the bar for
establishing judicial misconduct.

**McNeill Violations:**
- 167 disqualification violations documented
- 150 ex parte violations documented
- 504 total benchbook violations
- Pattern of bias against father/pro se litigant
- Ex parte orders entered August 8, 2025 (AFTER amendment effective date)
  based on unsworn motion with inadmissible hearsay

## Canon 4: Extrajudicial Activities
A judge may engage in activities to improve the law, legal system, and administration of justice.

## Canon 5: Political Activity Restrictions
A judge should refrain from inappropriate political activity.

## Canon 6: Financial Reporting
A judge shall report compensation for quasi-judicial and extrajudicial activities.

## Canon 7: Political Activity
Judges must minimize political entanglements and remain nonpartisan.

## Canon 8: Collective Activity
Judges may engage in collective activities concerning the law and legal system.

---

## VIOLATION MAPPING

| Canon | Subsection | Violation Count | Severity |
|-------|-----------|----------------|----------|
| 2(A) | Public confidence | 504 (total pattern) | CRITICAL |
| 2(B) | Relationship influence | Under investigation | HIGH |
| 3(A)(1) | Faithful to law | 161 procedural | CRITICAL |
| 3(A)(4) | Right to be heard | 150 ex parte | CRITICAL |
| 3(A)(4) | Ex parte communications | 150 documented | CRITICAL |
| 3(A)(5) | Bias/prejudice | 167 disqualification | CRITICAL |
| 3(B)(7) | Public comment | To be documented | MEDIUM |

---

*Source: Michigan Code of Judicial Conduct, as amended effective September 1, 2025.
Annotated version available at courts.michigan.gov.*
*Generated by LitigationOS Authority Expansion Engine*
"""
    write_md(os.path.join(pkg, "MCJC_FULL_CANON_REFERENCE.md"), content)
    log(f"  PKG06: MCJC full canon reference with 2025 amendment added")

# ============================================================
# 3. PKG12 — FOC ACT AUTHORITY
# ============================================================
def upgrade_pkg12():
    pkg = os.path.join(D99, "PKG12_FOC_OBJECTION")
    
    content = """# FRIEND OF THE COURT ACT — AUTHORITY REFERENCE

## MCL 552.501–552.535 | Applicable to FOC Objection

---

## KEY STATUTORY RIGHTS

### MCL 552.507(4) — De Novo Hearing Right (CRITICAL)
When a party files a timely written objection to a referee's recommended order within
**21 days** after service, the court **SHALL hold a de novo hearing**.

**What "de novo" means:**
- The judge starts FRESH — the referee's findings carry NO presumptive weight
- The judge cannot merely review the referee's record
- New evidence may be presented
- The hearing must be conducted by a JUDGE, not a referee
- The court cannot deny the hearing on technical grounds (formatting, etc.)

### MCL 552.511 — FOC Duties
The FOC SHALL:
- Investigate domestic relations matters referred by the court
- Make recommendations to the court
- Assist in enforcement of court orders
- Provide information to parties about their rights and obligations

**If the FOC failed any of these duties, document the failure in the objection.**

### MCL 552.517 — Grievance Procedures
Separate from objection. A party may file a grievance regarding FOC conduct, actions,
or inactions. The FOC must respond in writing within a reasonable time.

**Consider filing BOTH an objection (MCL 552.507) AND a grievance (MCL 552.517).**

---

## OBJECTION CHECKLIST

- [ ] Filed within 21 days of service of recommendation
- [ ] Written objection clearly identifies the objected-to portions
- [ ] States specific factual and legal basis for objection
- [ ] Requests de novo hearing before a judge (cite MCL 552.507(4))
- [ ] Includes supporting evidence/exhibits
- [ ] Certificate of service on all parties
- [ ] Fee waiver if applicable (MC 20)

## COMMON FOC INVESTIGATION FAILURES (grounds for objection)

1. **Inadequate investigation** — failed to interview key witnesses
2. **Bias** — predetermined outcome, ignored evidence favorable to father
3. **Failure to apply best interest factors** — MCL 722.23(a)-(l) not analyzed
4. **Failure to consider parenting time presumption** — MCL 722.27a(1)
5. **Reliance on inadmissible evidence** — hearsay, unsworn statements
6. **Failure to provide information** — did not inform pro se party of rights
7. **Procedural violations** — deviation from SCAO Custody & Parenting Time Investigation Manual

---

## SCAO INVESTIGATION STANDARDS

The Custody and Parenting Time Investigation Manual (November 2024) requires:
- Interviews with both parents
- Home study of both residences
- Assessment of all 12 best interest factors (MCL 722.23)
- Review of relevant records
- Analysis of each parent's ability to facilitate the child's relationship with the other parent
- Written report with specific findings on each factor

**Deviations from these standards are grounds for objection.**

---

*Authority: Friend of the Court Act, MCL 552.501-535; MCR 3.215; SCAO Custody & Parenting
Time Investigation Manual (2024)*
*Generated by LitigationOS Authority Expansion Engine*
"""
    write_md(os.path.join(pkg, "FOC_ACT_AUTHORITY_REFERENCE.md"), content)
    log(f"  PKG12: FOC Act authority reference added")

# ============================================================
# 4. PKG01 — MDHHS/CPS FRAMEWORK
# ============================================================
def upgrade_pkg01():
    pkg = os.path.join(D99, "PKG01_EMERGENCY_PARENTING_TIME")
    
    content = """# MDHHS / CHILD PROTECTION LAW FRAMEWORK

## MCL 722.621–722.638 | Applicable to Emergency Parenting Time Motion

---

## RELEVANCE TO THIS CASE

The mother is employed by the **Kent County Prosecutor's Office, Family Court Division**.
This creates multiple conflict-of-interest and due process dimensions:

1. **Prosecutorial resources** — Any use of prosecutorial office resources, databases,
   or relationships in the custody case constitutes a conflict of interest
2. **Mandatory reporting** — If court actors observed conditions warranting a CPS report
   and failed to report, this is a separate violation (MCL 722.623)
3. **CPS intersection** — Any CPS involvement must follow MCL 722.628 procedures,
   including informing parents of allegations and investigator identity

---

## KEY STATUTORY PROTECTIONS

### MCL 722.628 — Parental Rights During CPS Investigation
- Right to be informed of specific allegations
- Right to know the investigator's identity
- Right to legal counsel
- Right to review and appeal findings
- Right to remain together with child unless removal necessary for safety
- 24-hour commencement requirement

### MCL 722.623 — Mandatory Reporting
Professionals including social workers, law enforcement, and court officials
MUST report suspected child abuse or neglect. Failure to report is itself a violation.

### MCL 722.622 — Definitions
"Child abuse" requires nonaccidental physical/mental injury, sexual abuse, exploitation,
or maltreatment. "Child neglect" requires failure to provide adequate food, clothing,
shelter, or medical care.

**NOTE:** Exercising parenting time rights, filing motions, or being a pro se litigant
does NOT constitute abuse or neglect. Any suggestion otherwise is a weaponization of
the CPS system that itself constitutes a constitutional violation.

---

## STRATEGIC USE

If the opposing party has involved or threatened to involve CPS:
1. Document the CPS interaction and outcome (negative drug screen = CLEARED)
2. Cite MCL 722.628 parental rights in any response
3. If CPS was weaponized (false report to gain custody advantage), this supports:
   - PKG03 (Disqualification — bias)
   - PKG06 (JTC — judicial misconduct for enabling)
   - PKG08 (Contempt — bad faith litigation conduct)
   - PKG10 (Federal §1983 — state actors depriving rights)

---

*Authority: Michigan Child Protection Law, Act 238 of 1975 (MCL 722.621-638)*
*Generated by LitigationOS Authority Expansion Engine*
"""
    write_md(os.path.join(pkg, "MDHHS_CPS_FRAMEWORK.md"), content)
    log(f"  PKG01: MDHHS/CPS framework added")

# ============================================================
# 5. CROSS-PACKAGE STRATEGY LAYER
# ============================================================
def build_cross_strategy():
    content = """# CROSS-PACKAGE STRATEGIC COORDINATION LAYER

## 12-Package Unified Battle Plan

---

## I. OPTIMAL FILING SEQUENCE

The filing order matters — each package creates leverage for the next.

### Phase 1: ESTABLISH THE RECORD (File simultaneously)
| Order | Package | Purpose | Creates Leverage For |
|-------|---------|---------|---------------------|
| 1A | PKG01 — Emergency PT | Force hearing, expose 571-day separation | ALL packages |
| 1B | PKG11 — Spoliation | Preserve evidence before opposition destroys it | ALL packages |
| 1C | PKG12 — FOC Objection | Trigger de novo hearing (MCL 552.507(4)) | PKG01, PKG03 |

### Phase 2: ATTACK THE PROCESS (File within 7 days of Phase 1)
| Order | Package | Purpose | Creates Leverage For |
|-------|---------|---------|---------------------|
| 2A | PKG03 — Disqualify Judge | Remove biased judge BEFORE merits rulings | ALL remaining |
| 2B | PKG04 — Void Ex Parte Orders | Eliminate illegitimate orders | PKG01, PKG05, PKG08 |
| 2C | PKG02 — Vacate PPO | Remove weaponized PPO | PKG01, PKG08 |

### Phase 3: ESCALATE (File after trial court has acted on Phase 1-2)
| Order | Package | Purpose | Creates Leverage For |
|-------|---------|---------|---------------------|
| 3A | PKG05 — COA Brief | Appeal if trial court denies relief | PKG07 |
| 3B | PKG08 — Contempt | Enforce any orders gained in Phases 1-2 | PKG10 |

### Phase 4: NUCLEAR OPTIONS (File when state remedies exhausted or futile)
| Order | Package | Purpose | Creates Leverage For |
|-------|---------|---------|---------------------|
| 4A | PKG06 — JTC Investigation | Judicial accountability | PKG10 |
| 4B | PKG07 — MSC Application | Supreme Court intervention | PKG10 |
| 4C | PKG10 — Federal §1983 | Federal constitutional relief | Settlement |

### Phase 5: PARALLEL TRACKS (File independently as needed)
| Order | Package | Purpose |
|-------|---------|---------|
| 5A | PKG09 — Housing Complaint | Separate venue (60th District Court) |

---

## II. SHARED EXHIBIT STRATEGY

Many packages cite the same core evidence. Instead of duplicating exhibits,
create a **MASTER EXHIBIT BINDER** with Bates numbers that all packages reference.

### Core Exhibits (Used Across Multiple Packages)

| Bates # | Exhibit | Used In |
|---------|---------|---------|
| EX-001 | Ex Parte Orders (Aug 8, 2025) | PKG01,02,03,04,05,06,08,10 |
| EX-002 | Negative Drug Screen Results | PKG01,02,04,05,06,08,10 |
| EX-003 | Unsworn Motion (basis for ex parte) | PKG01,03,04,05,06,10 |
| EX-004 | 571+ Day Separation Timeline | PKG01,05,06,07,08,10 |
| EX-005 | FOC Investigation Report | PKG01,03,05,08,12 |
| EX-006 | Parenting Time Denial Communications | PKG01,05,08 |
| EX-007 | Court Docket (pattern of denials) | PKG03,05,06,07 |
| EX-008 | Mother's Employment Records (Kent Co PA) | PKG03,06,10 |
| EX-009 | Prior Motion Filings (retaliation pattern) | PKG03,05,06,10 |
| EX-010 | PPO Records | PKG02,05,06 |

### Package-Specific Exhibits

| Package | Unique Exhibits |
|---------|----------------|
| PKG05 (COA) | Lower court record, transcript excerpts, reproduced statutes |
| PKG06 (JTC) | Violation database export, statistical analysis |
| PKG07 (MSC) | COA decision (when available), bypass timeline |
| PKG09 (Housing) | Property photos, lease, code violation reports, communications |
| PKG10 (Federal) | Constitutional analysis, doctrine defense, immunity screening |

---

## III. WITNESS COORDINATION MATRIX

| Witness | Role | Packages | Testimony Focus |
|---------|------|----------|----------------|
| Andrew J. Pigors | Plaintiff/Father | ALL | Facts, separation, harm to child |
| Lincoln Watson | Minor Child | PKG01,05 | Best interests (through GAL if appointed) |
| FOC Investigator | Court Officer | PKG01,05,08,12 | Investigation adequacy, bias |
| Drug Testing Lab | Third Party | PKG01,02,04,05 | Negative results authentication |
| Neighbors/Family | Character | PKG01,05 | Father-child relationship, parenting |
| Court Clerk | Court Staff | PKG03,04 | Procedural irregularities, docket |

---

## IV. RES JUDICATA / COLLATERAL ESTOPPEL MAP

Findings established in one proceeding become binding in others:

| If Established In... | Then Binding For... | Finding |
|----------------------|--------------------|---------| 
| PKG01 (hearing on merits) | PKG05, PKG08 | Best interest factors favor father |
| PKG03 (disqualification granted) | PKG04, PKG06 | Bias established |
| PKG04 (orders voided) | PKG01, PKG02, PKG05 | Ex parte orders were invalid |
| PKG12 (de novo hearing) | PKG01, PKG05 | FOC recommendation overturned |
| COA (PKG05 appeal won) | PKG07, PKG10 | Constitutional violations confirmed |

---

## V. FEE WAIVER PROPAGATION

| Initial Filing | MC 20 Approval | Extends To |
|---------------|----------------|------------|
| PKG01 (14th Circuit) | Once approved | PKG02, PKG03, PKG04, PKG08, PKG11, PKG12 |
| PKG05 (Court of Appeals) | Separate MC 20 | PKG07 (MSC) |
| PKG09 (60th District) | Separate MC 20 | N/A |
| PKG10 (Federal — 28 USC 1915) | AO 240 IFP | N/A |

---

## VI. DEADLINE COORDINATION

| Package | Critical Deadline | Dependency |
|---------|------------------|------------|
| PKG05 — COA Brief | **April 15, 2026** | HARD DEADLINE — cannot miss |
| PKG07 — MSC | 42 days after COA decision | Or bypass if COA pending >180 days |
| PKG03 — Disqualify | 14 days from discovery of bias | File ASAP |
| PKG12 — FOC Objection | 21 days from FOC recommendation | Time-sensitive |
| PKG10 — Federal | 3-year statute of limitations | File after state remedies |
| PKG06 — JTC | No deadline (but sooner = more weight) | File with Phase 4 |

---

## VII. SETTLEMENT LEVERAGE ANALYSIS

The combined weight of 12 packages creates exponential settlement pressure:

| Leverage Point | Source Packages | Pressure Type |
|---------------|----------------|--------------|
| 571+ days without hearing | PKG01,05,10 | Constitutional / emotional |
| Judicial misconduct documented | PKG03,06 | Career threat to judge |
| Federal civil rights exposure | PKG10 | Financial (42 USC 1988 fees) |
| PPO weaponization evidence | PKG02,05,06 | Credibility destruction |
| Prosecutorial conflict of interest | PKG10,06 | Institutional embarrassment |
| Contempt findings | PKG08 | Enforcement power |
| Public record of all filings | ALL | Reputational |

**Optimal settlement window:** After PKG01-PKG04 filed but before PKG10 (federal).
The threat of federal action with documented state-court failures is maximum leverage.

---

*Generated by LitigationOS Cross-Package Strategy Engine*
"""
    write_md(os.path.join(D99, "CROSS_PACKAGE_STRATEGY.md"), content)
    log(f"  Cross-package strategy layer built")

# ============================================================
# 6. PKG09 — HOUSING LAW EXPANSION
# ============================================================
def upgrade_pkg09():
    pkg = os.path.join(D99, "PKG09_HOUSING_COMPLAINT")
    content = """# HOUSING LAW AUTHORITY REFERENCE

## Michigan Landlord-Tenant Law + Federal Fair Housing Act

---

## CORE MICHIGAN STATUTES

### MCL 554.139 — Implied Warranty of Habitability
In every residential lease, the landlord covenants:
(a) Premises and common areas are **fit for use intended**
(b) Keep premises in **reasonable repair** during term
(c) Comply with applicable **health and safety laws**

Exception: Disrepair caused by tenant's willful/irresponsible conduct.

### MCL 600.5720 — Tenant Remedies
When landlord breaches habitability:
- Recover **damages**
- **Rent abatement** for uninhabitable period
- **Equitable relief** (injunction ordering repairs)
- **Rent withholding** after proper notice

### MCL 554.601a–.641 — Truth in Renting Act
- MCL 554.633: Lease provisions violating tenant rights are **void and unenforceable**
- MCL 554.636: Tenant may recover **actual damages or $250** (whichever greater)
  plus **reasonable attorney's fees**

### 42 USC § 3604 — Fair Housing Act (Federal)
Prohibits discrimination in housing based on race, color, religion, sex,
familial status, national origin, disability. Available if discrimination angle exists.

---

## CAUSE OF ACTION CHECKLIST

- [ ] Identify specific habitability failures (with dates and photos)
- [ ] Document all communications with landlord requesting repairs
- [ ] Calculate rent abatement amount (uninhabitable days x daily rent)
- [ ] Identify Truth in Renting Act violations in lease
- [ ] Check for discrimination indicators (Fair Housing Act)
- [ ] Verify proper venue: 60th District Court, Muskegon County

---

*Authority: MCL 554.139, MCL 600.5720, MCL 554.601a-641, 42 USC 3604*
"""
    write_md(os.path.join(pkg, "HOUSING_LAW_AUTHORITY.md"), content)
    log(f"  PKG09: Housing law authority reference added")

# ============================================================
# RUN ALL UPGRADES
# ============================================================
def run_all():
    log("=" * 60)
    log("PACKAGE UPGRADE ENGINE — INJECTING AUTHORITY")
    log("=" * 60)
    
    upgrade_pkg10()
    upgrade_pkg06()
    upgrade_pkg12()
    upgrade_pkg01()
    upgrade_pkg09()
    build_cross_strategy()
    
    # Count total new files
    new_files = [
        "PKG10_FEDERAL_1983/DOCTRINE_DEFENSE_MATRIX.md",
        "PKG10_FEDERAL_1983/IMMUNITY_ABSTENTION_SCREENING.md",
        "PKG06_JTC_COMPLAINT/MCJC_FULL_CANON_REFERENCE.md",
        "PKG12_FOC_OBJECTION/FOC_ACT_AUTHORITY_REFERENCE.md",
        "PKG01_EMERGENCY_PARENTING_TIME/MDHHS_CPS_FRAMEWORK.md",
        "PKG09_HOUSING_COMPLAINT/HOUSING_LAW_AUTHORITY.md",
        "CROSS_PACKAGE_STRATEGY.md",
        "AUTHORITY_EXPANSION.json",
        "DOCTRINE_DEFENSE_MATRIX.json",
    ]
    
    log(f"\n  NEW FILES ADDED: {len(new_files)}")
    for f in new_files:
        path = os.path.join(D99, f)
        if os.path.exists(path):
            size = os.path.getsize(path) / 1024
            log(f"    {f}: {size:.1f}KB")
    
    log("=" * 60)
    log("PACKAGE UPGRADES COMPLETE")
    log("=" * 60)

if __name__ == "__main__":
    run_all()