from __future__ import annotations
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Callable, Optional
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]

@dataclass
class ReplayEntry:
    run_id: str
    cycle_id: str
    event_id: str
    operator_id: str
    from_state: str
    to_state: str
    guard_results: Dict[str, bool] = field(default_factory=dict)
    input_refs: List[str] = field(default_factory=list)
    output_refs: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    timestamp_utc: str = ""
    lane: str = "MULTI"
    case_id: str = ""
    integrity_key: str = ""

class RuntimeBootstrap:
    def __init__(self, root: Path):
        self.root = root
        self.runtime_dir = root / "runtime"
        self.logs_dir = root / "logs"
        self.manifests_dir = root / "manifests"
        self.validation_dir = root / "validation"
        self.logs_dir.mkdir(exist_ok=True, parents=True)
        self.manifests_dir.mkdir(exist_ok=True, parents=True)
        self.validation_dir.mkdir(exist_ok=True, parents=True)

        self.state = "STATE.INTAKE_READY"
        self.run_id = "RUN_SEED_001"
        self.cycle_id = "CYCLE_SEED_001"
        self.replay_path = self.logs_dir / "replay_log.seed.jsonl"
        self.replay_path.write_text("", encoding="utf-8")

        self.states = self._load_json(self.runtime_dir / "state_registry.seed.json")
        self.guards = self._load_json(self.runtime_dir / "guard_registry.seed.json")
        self.operators = self._load_json(self.runtime_dir / "operator_catalog.seed.json")
        self.transitions = self._load_json(self.runtime_dir / "transition_table.seed.json")

        self.operator_handlers = self._build_operator_handlers()
        self.guard_registry = {g["guard_id"]: self._default_guard for g in self.guards["guards"]}

        self.manifest = {
            "run_id": self.run_id,
            "cycle_id": self.cycle_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "artifacts_emitted": [],
            "bundle_verified": False,
            "replay_log_path": str(self.replay_path),
            "convergence_metrics": {},
            "next_cycle_targets": []
        }

    def _load_json(self, path: Path) -> Dict[str, Any]:
        return json.loads(path.read_text(encoding="utf-8"))

    def _default_guard(self, event: Dict[str, Any], context: Dict[str, Any]) -> tuple[bool, str]:
        # Seed implementation: returns True if event payload contains the expected proof hint, else soft-fails
        gid = context.get("guard_id", "")
        payload = event.get("payload", {})
        hints = payload.get("guard_hints", {})
        if gid in hints:
            return bool(hints[gid]), "payload guard_hints"
        # permissive seed default for bootstrapping
        return True, "seed default pass"

    def _build_operator_handlers(self) -> Dict[str, Callable[[Dict[str, Any], Dict[str, Any]], Dict[str, Any]]]:
        def pure_echo(event: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:
            return {"ok": True, "echo": {"event_type": event.get("event_type"), "state": self.state}}

        def assemble_packet(event: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:
            out = self.root / "artifacts" / "PACKET_SEED.txt"
            out.write_text("Seed packet artifact generated by runtime_bootstrap.py\n", encoding="utf-8")
            self.manifest["artifacts_emitted"].append(str(out))
            return {"ok": True, "artifact": str(out)}

        def emit_cyclepack(event: Dict[str, Any], ctx: Dict[str, Any]) -> Dict[str, Any]:
            # Seed placeholder; actual zip handled by outer build process
            self.manifest["bundle_verified"] = True
            return {"ok": True, "bundle_verified": True}

        handlers = {}
        for op in self.operators["operators"]:
            oid = op["operator_id"]
            if oid == "OP.DRAFT.ASSEMBLE_PACKET":
                handlers[oid] = assemble_packet
            elif oid == "OP.PACKAGE.EMIT_CYCLEPACK":
                handlers[oid] = emit_cyclepack
            else:
                handlers[oid] = pure_echo
        return handlers

    def _matching_transitions(self, event_type: str) -> List[Dict[str, Any]]:
        rows = [
            t for t in self.transitions["transitions"]
            if t["from_state"] == self.state and t["event"] == event_type
        ]
        rows.sort(key=lambda x: (x.get("priority", 0), x["transition_id"]))
        return rows

    def _eval_guards(self, trow: Dict[str, Any], event: Dict[str, Any]) -> tuple[bool, Dict[str, bool], List[str]]:
        results: Dict[str, bool] = {}
        reasons: List[str] = []
        for gid in trow.get("guards_all", []):
            fn = self.guard_registry.get(gid, self._default_guard)
            passed, reason = fn(event, {"guard_id": gid})
            results[gid] = passed
            reasons.append(f"{gid}: {reason}")
            if not passed:
                return False, results, reasons
        return True, results, reasons

    def _write_replay(self, entry: ReplayEntry) -> None:
        line = json.dumps(entry.__dict__, ensure_ascii=False)
        with self.replay_path.open("a", encoding="utf-8") as f:
            f.write(line + "\n")

    def process_event(self, event: Dict[str, Any]) -> Dict[str, Any]:
        event_type = event["event_type"]
        candidates = self._matching_transitions(event_type)
        if not candidates:
            return {"ok": False, "error": "NO_MATCH", "state": self.state, "event_type": event_type}

        trow = candidates[0]
        passed, guard_results, guard_reasons = self._eval_guards(trow, event)
        if not passed:
            replay = ReplayEntry(
                run_id=self.run_id, cycle_id=self.cycle_id, event_id=event.get("event_id","EVT_SEED"),
                operator_id="(guards)", from_state=self.state, to_state=trow.get("on_fail_state") or self.state,
                guard_results=guard_results, errors=["GUARD_FAIL"], warnings=guard_reasons,
                timestamp_utc=datetime.now(timezone.utc).isoformat()
            )
            self._write_replay(replay)
            self.state = trow.get("on_fail_state") or self.state
            return {"ok": False, "error": "GUARD_FAIL", "state": self.state, "guard_results": guard_results}

        current_state = self.state
        for oid in trow["operator_seq"]:
            handler = self.operator_handlers[oid]
            try:
                out = handler(event, {"transition_id": trow["transition_id"]})
                replay = ReplayEntry(
                    run_id=self.run_id, cycle_id=self.cycle_id, event_id=event.get("event_id","EVT_SEED"),
                    operator_id=oid, from_state=current_state, to_state=trow["to_state"],
                    guard_results=guard_results, output_refs=[json.dumps(out)], warnings=guard_reasons,
                    timestamp_utc=datetime.now(timezone.utc).isoformat(), lane=event.get("lane", "MULTI"),
                    case_id=event.get("case_id","")
                )
                self._write_replay(replay)
            except Exception as e:
                replay = ReplayEntry(
                    run_id=self.run_id, cycle_id=self.cycle_id, event_id=event.get("event_id","EVT_SEED"),
                    operator_id=oid, from_state=current_state, to_state=trow.get("on_fail_state") or current_state,
                    guard_results=guard_results, errors=[f"OPERATOR_ERROR: {e}"],
                    timestamp_utc=datetime.now(timezone.utc).isoformat(), lane=event.get("lane","MULTI")
                )
                self._write_replay(replay)
                self.state = trow.get("on_fail_state") or current_state
                return {"ok": False, "error": "OPERATOR_ERROR", "state": self.state}

        self.state = trow["to_state"]
        return {"ok": True, "state": self.state, "transition_id": trow["transition_id"]}

    def finalize(self) -> None:
        manifest_path = self.manifests_dir / "run_manifest.seed.json"
        self.manifest["generated_at"] = datetime.now(timezone.utc).isoformat()
        manifest_path.write_text(json.dumps(self.manifest, indent=2), encoding="utf-8")

def main():
    rt = RuntimeBootstrap(ROOT)
    seed_events = [
        {"event_id": "EVT_0001", "event_type": "FILE_DISCOVERED", "lane": "MULTI", "case_id": "24-01507-DC", "payload": {}},
        {"event_id": "EVT_0002", "event_type": "ORDER_PARSE_OK", "lane": "TRIAL", "case_id": "24-01507-DC",
         "payload": {"guard_hints": {"G.RECORD.CAPTION_PRESENT": True, "G.RECORD.CASE_ID_PRESENT": True, "G.RECORD.ORDER_DATE_PRESENT": True}}},
        {"event_id": "EVT_0003", "event_type": "ISSUES_EXTRACTED", "lane": "TRIAL", "case_id": "24-01507-DC",
         "payload": {"guard_hints": {"G.EVIDENCE.FACT_ATOMS_MIN_READY": True, "G.AUTHORITY.MIN_TRIPLES_READY": True}}},
        {"event_id": "EVT_0004", "event_type": "PACKET_BUILD_REQUEST", "lane": "TRIAL", "case_id": "24-01507-DC",
         "payload": {"guard_hints": {"G.VEHICLE.PRIMARY_SELECTED": True}}},
        {"event_id": "EVT_0005", "event_type": "VALIDATE_PACKET", "lane": "TRIAL", "case_id": "24-01507-DC",
         "payload": {"guard_hints": {"G.DRAFT.PACKET_ASSEMBLED": True}}},
        {"event_id": "EVT_0006", "event_type": "EMIT_BUNDLE", "lane": "TRIAL", "case_id": "24-01507-DC",
         "payload": {"guard_hints": {"G.VALIDATE.PACKET_PASS": True, "G.PACKAGE.BUNDLE_VERIFIED": True}}},
    ]

    print("Initial state:", rt.state)
    for ev in seed_events:
        result = rt.process_event(ev)
        print(ev["event_type"], "->", result)
    rt.finalize()
    print("Final state:", rt.state)
    print("Replay:", rt.replay_path)
    print("Manifest:", ROOT / "manifests" / "run_manifest.seed.json")

if __name__ == "__main__":
    main()
