// OMEGA-INFINITY Neo4j Import Script
// Generated by _neo4j_export_runner.py

// --- Constraints ---
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Case) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Lane) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Party) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Judge) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Attorney) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Evidence) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Filing) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Form) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Rule) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Violation) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Witness) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Event) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:Exhibit) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (n:BestInterestFactor) REQUIRE n.id IS UNIQUE;

// --- Node imports ---

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Case.csv' AS row
MERGE (n:Case {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Lane.csv' AS row
MERGE (n:Lane {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Party.csv' AS row
MERGE (n:Party {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Judge.csv' AS row
MERGE (n:Judge {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Attorney.csv' AS row
MERGE (n:Attorney {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Evidence.csv' AS row
MERGE (n:Evidence {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Filing.csv' AS row
MERGE (n:Filing {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Form.csv' AS row
MERGE (n:Form {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Rule.csv' AS row
MERGE (n:Rule {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Violation.csv' AS row
MERGE (n:Violation {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Witness.csv' AS row
MERGE (n:Witness {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Event.csv' AS row
MERGE (n:Event {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_Exhibit.csv' AS row
MERGE (n:Exhibit {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

LOAD CSV WITH HEADERS FROM 'file:///export/nodes_BestInterestFactor.csv' AS row
MERGE (n:BestInterestFactor {id: row.`:ID`})
SET n += row, n.label = row.`:LABEL`;

// --- Edge imports ---

LOAD CSV WITH HEADERS FROM 'file:///export/edges_BELONGS_TO_LANE.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:BELONGS_TO_LANE]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_CITES_AUTHORITY.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:CITES_AUTHORITY]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_COMMITTED_BY.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:COMMITTED_BY]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_EVIDENCE_FOR_FILING.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:EVIDENCE_FOR_FILING]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_EVIDENCE_IN_LANE.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:EVIDENCE_IN_LANE]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_FILED_IN.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:FILED_IN]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_HAS_VIOLATION.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:HAS_VIOLATION]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_INVOLVES_PARTY.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:INVOLVES_PARTY]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_NEXT_EVENT.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:NEXT_EVENT]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_OCCURRED_IN.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:OCCURRED_IN]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_PRESIDED_BY.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:PRESIDED_BY]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_REPRESENTED_BY.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:REPRESENTED_BY]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_TESTIFIED_IN.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:TESTIFIED_IN]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_USES_FORM.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:USES_FORM]->(b);

LOAD CSV WITH HEADERS FROM 'file:///export/edges_VIOLATES_RULE.csv' AS row
MATCH (a {id: row.`:START_ID`})
MATCH (b {id: row.`:END_ID`})
MERGE (a)-[:VIOLATES_RULE]->(b);