// ============================================================================
// LitigationOS OMEGA-INFINITY — Neo4j Node Import Script
// ============================================================================
// Version: 4.0
// Usage: Run in Neo4j Browser or cypher-shell after CSV export
// Prerequisites: CSV files generated by scripts/omega_neo4j_export.py
//
// IMPORTANT: Copy CSV files to the Neo4j import directory before running:
//   - Neo4j Desktop: <neo4j-home>/import/
//   - Neo4j Aura: Upload via Aura console
//   - Docker: Mount volume to /var/lib/neo4j/import/
// ============================================================================

// ----------------------------------------------------------------------------
// STEP 0: Clean slate (optional — uncomment to wipe existing graph)
// ----------------------------------------------------------------------------
// MATCH (n) DETACH DELETE n;

// ----------------------------------------------------------------------------
// STEP 1: Create Constraints and Indexes
// ----------------------------------------------------------------------------

// Uniqueness constraints (also create implicit indexes)
CREATE CONSTRAINT case_unique IF NOT EXISTS FOR (c:Case) REQUIRE c.case_number IS UNIQUE;
CREATE CONSTRAINT lane_unique IF NOT EXISTS FOR (l:Lane) REQUIRE l.lane_id IS UNIQUE;
CREATE CONSTRAINT party_unique IF NOT EXISTS FOR (p:Party) REQUIRE p.name IS UNIQUE;
CREATE CONSTRAINT judge_unique IF NOT EXISTS FOR (j:Judge) REQUIRE j.name IS UNIQUE;
CREATE CONSTRAINT attorney_unique IF NOT EXISTS FOR (a:Attorney) REQUIRE a.bar_number IS UNIQUE;
CREATE CONSTRAINT claim_unique IF NOT EXISTS FOR (cl:Claim) REQUIRE cl.claim_id IS UNIQUE;
CREATE CONSTRAINT evidence_unique IF NOT EXISTS FOR (e:Evidence) REQUIRE e.id IS UNIQUE;
CREATE CONSTRAINT filing_unique IF NOT EXISTS FOR (f:Filing) REQUIRE f.vehicle_name IS UNIQUE;
CREATE CONSTRAINT form_unique IF NOT EXISTS FOR (fm:Form) REQUIRE fm.form_number IS UNIQUE;
CREATE CONSTRAINT rule_unique IF NOT EXISTS FOR (r:Rule) REQUIRE r.citation IS UNIQUE;
CREATE CONSTRAINT violation_unique IF NOT EXISTS FOR (v:Violation) REQUIRE v.violation_id IS UNIQUE;
CREATE CONSTRAINT witness_unique IF NOT EXISTS FOR (w:Witness) REQUIRE w.name IS UNIQUE;
CREATE CONSTRAINT event_unique IF NOT EXISTS FOR (ev:Event) REQUIRE ev.event_id IS UNIQUE;

// Performance indexes for frequent query patterns
CREATE INDEX evidence_lane IF NOT EXISTS FOR (e:Evidence) ON (e.lane);
CREATE INDEX evidence_category IF NOT EXISTS FOR (e:Evidence) ON (e.category);
CREATE INDEX evidence_relevance IF NOT EXISTS FOR (e:Evidence) ON (e.relevance_score);
CREATE INDEX rule_citation IF NOT EXISTS FOR (r:Rule) ON (r.citation);
CREATE INDEX rule_type IF NOT EXISTS FOR (r:Rule) ON (r.rule_type);
CREATE INDEX violation_type IF NOT EXISTS FOR (v:Violation) ON (v.violation_type);
CREATE INDEX violation_severity IF NOT EXISTS FOR (v:Violation) ON (v.severity);
CREATE INDEX event_date IF NOT EXISTS FOR (ev:Event) ON (ev.event_date);
CREATE INDEX event_type IF NOT EXISTS FOR (ev:Event) ON (ev.event_type);
CREATE INDEX filing_readiness IF NOT EXISTS FOR (f:Filing) ON (f.readiness_score);
CREATE INDEX filing_lane IF NOT EXISTS FOR (f:Filing) ON (f.lane);
CREATE INDEX claim_lane IF NOT EXISTS FOR (cl:Claim) ON (cl.lane);
CREATE INDEX claim_status IF NOT EXISTS FOR (cl:Claim) ON (cl.status);
CREATE INDEX witness_lane IF NOT EXISTS FOR (w:Witness) ON (w.lane);

// ----------------------------------------------------------------------------
// STEP 2: Import Lane Nodes (6 lanes — static)
// ----------------------------------------------------------------------------

LOAD CSV WITH HEADERS FROM 'file:///lanes.csv' AS row
MERGE (l:Lane {lane_id: row.lane_id})
SET l.name = row.name,
    l.meek_signal = row.meek_signal,
    l.case_number = row.case_number,
    l.description = row.description,
    l.color = row.color;

// ----------------------------------------------------------------------------
// STEP 3: Import Case Nodes
// ----------------------------------------------------------------------------

LOAD CSV WITH HEADERS FROM 'file:///cases.csv' AS row
MERGE (c:Case {case_number: row.case_number})
SET c.case_type = row.case_type,
    c.court = row.court,
    c.lane = row.lane,
    c.caption = row.caption,
    c.filing_date = row.filing_date,
    c.status = row.status;

// ----------------------------------------------------------------------------
// STEP 4: Import Party Nodes
// ----------------------------------------------------------------------------

LOAD CSV WITH HEADERS FROM 'file:///parties.csv' AS row
MERGE (p:Party {name: row.name})
SET p.role = row.role,
    p.address = row.address,
    p.phone = row.phone,
    p.email = row.email;

// ----------------------------------------------------------------------------
// STEP 5: Import Judge Nodes
// ----------------------------------------------------------------------------

LOAD CSV WITH HEADERS FROM 'file:///judges.csv' AS row
MERGE (j:Judge {name: row.name})
SET j.court = row.court,
    j.bar_number = row.bar_number,
    j.division = row.division;

// ----------------------------------------------------------------------------
// STEP 6: Import Attorney Nodes
// ----------------------------------------------------------------------------

LOAD CSV WITH HEADERS FROM 'file:///attorneys.csv' AS row
MERGE (a:Attorney {bar_number: row.bar_number})
SET a.name = row.name,
    a.firm = row.firm,
    a.status = row.status,
    a.represents = row.represents;

// ----------------------------------------------------------------------------
// STEP 7: Import Claim Nodes
// ----------------------------------------------------------------------------

:auto LOAD CSV WITH HEADERS FROM 'file:///claims.csv' AS row
CALL { WITH row
  MERGE (cl:Claim {claim_id: row.claim_id})
  SET cl.claim_type = row.claim_type,
      cl.description = row.description,
      cl.status = row.status,
      cl.vehicle_name = row.vehicle_name,
      cl.lane = row.lane,
      cl.strength_score = CASE WHEN row.strength_score IS NOT NULL
                               THEN toFloat(row.strength_score) ELSE NULL END
} IN TRANSACTIONS OF 5000 ROWS;

// ----------------------------------------------------------------------------
// STEP 8: Import Evidence Nodes (large table — batched)
// ----------------------------------------------------------------------------

:auto LOAD CSV WITH HEADERS FROM 'file:///evidence.csv' AS row
CALL { WITH row
  MERGE (e:Evidence {id: row.id})
  SET e.source_file = row.source_file,
      e.category = row.category,
      e.lane = row.lane,
      e.quote_text = LEFT(row.quote_text, 500),
      e.relevance_score = CASE WHEN row.relevance_score IS NOT NULL
                               THEN toFloat(row.relevance_score) ELSE 0.0 END,
      e.date_extracted = row.date_extracted,
      e.authentication_status = COALESCE(row.authentication_status, 'Pending')
} IN TRANSACTIONS OF 5000 ROWS;

// ----------------------------------------------------------------------------
// STEP 9: Import Filing Nodes
// ----------------------------------------------------------------------------

:auto LOAD CSV WITH HEADERS FROM 'file:///filings.csv' AS row
CALL { WITH row
  MERGE (f:Filing {vehicle_name: row.vehicle_name})
  SET f.readiness_score = CASE WHEN row.readiness_score IS NOT NULL
                               THEN toFloat(row.readiness_score) ELSE 0.0 END,
      f.status = row.status,
      f.lane = row.lane,
      f.filing_type = row.filing_type,
      f.target_court = row.target_court,
      f.evidence_count = CASE WHEN row.evidence_count IS NOT NULL
                              THEN toInteger(row.evidence_count) ELSE 0 END
} IN TRANSACTIONS OF 5000 ROWS;

// ----------------------------------------------------------------------------
// STEP 10: Import Form Nodes (from court_forms.db export)
// ----------------------------------------------------------------------------

LOAD CSV WITH HEADERS FROM 'file:///forms.csv' AS row
MERGE (fm:Form {form_number: row.form_number})
SET fm.form_title = row.form_title,
    fm.category = row.category,
    fm.division = row.division,
    fm.url = row.url,
    fm.instructions = row.instructions;

// ----------------------------------------------------------------------------
// STEP 11: Import Rule / Authority Nodes
// ----------------------------------------------------------------------------

:auto LOAD CSV WITH HEADERS FROM 'file:///rules.csv' AS row
CALL { WITH row
  MERGE (r:Rule {citation: row.citation})
  SET r.rule_type = row.rule_type,
      r.source = row.source,
      r.description = row.description,
      r.relevance_count = CASE WHEN row.relevance_count IS NOT NULL
                               THEN toInteger(row.relevance_count) ELSE 0 END
} IN TRANSACTIONS OF 5000 ROWS;

// ----------------------------------------------------------------------------
// STEP 12: Import Violation Nodes
// ----------------------------------------------------------------------------

:auto LOAD CSV WITH HEADERS FROM 'file:///violations.csv' AS row
CALL { WITH row
  MERGE (v:Violation {violation_id: row.violation_id})
  SET v.violation_type = row.violation_type,
      v.mcr_rule = row.mcr_rule,
      v.severity = row.severity,
      v.date_occurred = row.date_occurred,
      v.description = row.description,
      v.evidence_refs = row.evidence_refs
} IN TRANSACTIONS OF 5000 ROWS;

// ----------------------------------------------------------------------------
// STEP 13: Import Witness Nodes
// ----------------------------------------------------------------------------

:auto LOAD CSV WITH HEADERS FROM 'file:///witnesses.csv' AS row
CALL { WITH row
  MERGE (w:Witness {name: row.name})
  SET w.role = row.role,
      w.lane = row.lane,
      w.testimony_count = CASE WHEN row.testimony_count IS NOT NULL
                               THEN toInteger(row.testimony_count) ELSE 0 END
} IN TRANSACTIONS OF 5000 ROWS;

// ----------------------------------------------------------------------------
// STEP 14: Import Event Nodes (large table — batched)
// ----------------------------------------------------------------------------

:auto LOAD CSV WITH HEADERS FROM 'file:///events.csv' AS row
CALL { WITH row
  MERGE (ev:Event {event_id: row.event_id})
  SET ev.event_date = row.event_date,
      ev.event_type = row.event_type,
      ev.description = row.description,
      ev.lane = row.lane,
      ev.source_table = row.source_table
} IN TRANSACTIONS OF 5000 ROWS;

// ----------------------------------------------------------------------------
// STEP 15: Verification Queries
// ----------------------------------------------------------------------------

// Count all nodes by label
CALL db.labels() YIELD label
CALL apoc.cypher.run('MATCH (n:`' + label + '`) RETURN count(n) AS count', {}) YIELD value
RETURN label, value.count AS nodeCount
ORDER BY nodeCount DESC;

// Quick sanity checks
MATCH (l:Lane) RETURN count(l) AS lane_count;    // Expect 6
MATCH (c:Case) RETURN count(c) AS case_count;    // Expect 4-6
MATCH (p:Party) RETURN count(p) AS party_count;  // Expect ~5
MATCH (j:Judge) RETURN count(j) AS judge_count;  // Expect 1-2
